#!/usr/bin/env python3
"""Re-run the actual six-loop programs without modifying accepted evidence."""
from pathlib import Path
import argparse,hashlib,json,shutil,subprocess,sys
HERE=Path(__file__).resolve().parent
PHASES=('A1','A2','B1','B2','C1','C2')
def main(output,optimized=False):
    out=Path(output).expanduser().resolve()
    if out==HERE or HERE in out.parents:raise ValueError('Use an output directory outside the accepted round15 tree')
    if out.exists():raise ValueError('Output already exists; accepted or earlier runs will not be overwritten')
    from build_site_data import verify_gates
    verify_gates();out.mkdir(parents=True);source=out/'source'
    # Copy only source/evidence directories needed by the commands; no website or nested archives.
    for role in ('forward','backward','advisor'):
        shutil.copytree(HERE/role,source/role,ignore=shutil.ignore_patterns('__pycache__','*.pyc'))
    python=[sys.executable]+(['-O'] if optimized else [])
    runs=[]
    def execute(label,script,args,expected_dir=None):
        target=out/'runs'/label;target.mkdir(parents=True)
        command=python+[str(source/script)]+[str(x) for x in args(target)]
        proc=subprocess.run(command,cwd=source/script.parent,capture_output=True,text=True,timeout=180)
        (target/'stdout.txt').write_text(proc.stdout);(target/'stderr.txt').write_text(proc.stderr)
        record={'label':label,'command':command,'returncode':proc.returncode,'byte_matches':{}}
        if proc.returncode:raise RuntimeError('Research command failed '+label+': '+proc.stderr[-1000:])
        if expected_dir:
            for p in sorted((HERE/expected_dir).glob('*')):
                if not p.is_file():continue
                actual=target/p.name
                if not actual.is_file() or actual.read_bytes()!=p.read_bytes():raise ValueError('Reproduced bytes differ '+label+'/'+p.name)
                record['byte_matches'][p.name]=hashlib.sha256(actual.read_bytes()).hexdigest()
        reports=[json.loads(p.read_bytes()) for p in target.glob('*.json') if p.name in ('results.json','independent_review.json','independent_bound_review.json','independent_state_review.json','independent_variational_review.json')]
        if not reports or any(r.get('status')!='passed' for r in reports):raise ValueError('Missing/failed semantic report '+label)
        runs.append(record)
    for phase in PHASES:
        execute('forward-'+phase,Path('forward')/phase/('run_'+phase.lower()+'.py'),lambda target:[target],Path('forward')/phase/'output')
        if phase=='A1':script=Path('backward/A1/verify_cover.py');args=lambda target:[source/'forward/A1/output/cover.json',source/'forward/A1',target]
        elif phase=='A2':script=Path('backward/A2/verify_adaptive.py');args=lambda target:[source/'forward',target]
        elif phase=='B1':script=Path('backward/B1/verify_cube.py');args=lambda target:[source/'forward/B1/graph.json',source/'forward/B1/cube.py',target]
        elif phase=='B2':script=Path('backward/B2/verify_series.py');args=lambda target:[source/'forward',target]
        elif phase=='C1':script=Path('backward/C1/verify_bound.py');args=lambda target:[source/'forward',target]
        else:script=Path('backward/C2/verify_variational.py');args=lambda target:[source/'forward',target]
        # C1 state report is generated by its own independent program below.
        expected=Path('backward')/phase/'output'
        if phase=='C1':
            execute('backward-'+phase,script,args)
            p=out/'runs/backward-C1/independent_bound_review.json'
            if p.read_bytes()!=(HERE/expected/'independent_bound_review.json').read_bytes():raise ValueError('C1 independent evidence changed')
            execute('backward-C1-state',Path('backward/C1/state_review.py'),lambda target:[source/'forward/B1/graph.json',source/'advisor',target])
            p=out/'runs/backward-C1-state/independent_state_review.json'
            if p.read_bytes()!=(HERE/expected/'independent_state_review.json').read_bytes():raise ValueError('Independent state evidence changed')
        else:execute('backward-'+phase,script,args,expected)
    report={'status':'passed','mode':'optimized' if optimized else 'ordinary','research_loops':6,'executed_programs':len(runs),'runs':runs,'scope':'Actual accepted phase programs and semantic outcomes; source and exact output bytes preserved. Ordinary/optimized runs are the same gate set.'}
    (out/'reproduction.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='runs'}));return report
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--optimized',action='store_true');a=p.parse_args();main(a.output,a.optimized)
