"""Routes, reproducible project briefs, historical guides, and study advice."""
paths=[]
def route(i,name,description,targets,evidence):
    by={c['id']:c for c in chapters}
    found=set()
    def include(cid):
        if cid in found: return
        for p in by[cid]['prereqs']: include(p)
        found.add(cid)
    for n in targets: include(f'P{n:03}')
    paths.append(dict(id=i,name=name,description=description,chapters=[c['id'] for c in chapters if c['id'] in found],evidence=evidence))
route('combined','The combined physics atlas','All 108 chapters in a prerequisite-respecting sequence. A multi-year reference and study program; choose a focused branch before attempting research.',range(1,109),['A derivation notebook and measured or simulated examples','One substantial replication in your chosen specialty','A proposal with a testable question and explicit limitations'])
route('foundations','Start from the beginning','Arithmetic, core mathematics, measurement, and introductory mechanics. Advanced mathematics is introduced later when a branch needs it.',[1,2,3,4,5,6,7,8,9,10,13,14,15,19,20,21,22,23,24],['Unit-consistent solutions with diagrams','An uncertainty budget and one numerical-versus-analytic comparison'])
route('mathematics','The mathematical toolkit','A dedicated mathematics sequence from arithmetic to manifolds and symmetry. Revisit advanced chapters while studying their physical applications.',range(1,19),['Solve an ODE, a boundary-value PDE, and an eigenproblem','Distinguish coordinates, geometric objects, and invariant statements'])
route('mechanics','Mechanics and Newton','Motion, analytical dynamics, fluids, gravitation, and source-guided Newton reading.',list(range(19,33))+[97,98],['An orbit and energy-conservation study','A primary-source comparison of a Newton proposition'])
route('electromagnetism','Fields, circuits, and Tesla','Electrostatics through Maxwell theory, wave propagation, and electromagnetic machinery, followed by documented Tesla works.',list(range(33,47))+[102,103],['A converged field solution and resonant-circuit report','A patent-claim audit with a modern energy budget'])
route('quantum','Quantum physics and information','Quantum mechanics, atomic systems, quantum computation, error correction, and a bridge to fields.',list(range(60,75))+[105,106,107],['A wavefunction calculation checked against an analytic limit','An entanglement or open-system experiment in simulation','A critical reading of a recent quantum paper'])
route('gravity','Relativity, gravity, and cosmology','Special and general relativity, black holes, gravitational waves, cosmology, and carefully labeled quantum-gravity directions.',list(range(75,83))+[99,100,105,106,107],['A metric calculation and Newtonian-limit check','A reproducible public gravitational-wave or cosmology analysis'])
route('thermal','Light, heat, and collective behavior','Waves, optics, thermodynamics, statistical physics, and nonequilibrium transport.',range(47,60),['A diffraction comparison with stated approximations','A thermal or statistical simulation with finite-size and sampling checks'])
route('materials','Quantum materials and condensed matter','Solids, semiconductors, magnetism, superconductivity, topology, and computational many-body methods.',list(range(83,88))+[105,106,107],['Band-structure or transport reproduction using an established package','A finite-size, k-point, or basis convergence report'])
route('particle','Particles, fields, nuclei, and plasma','The Standard Model, field theory, nuclear and neutrino physics, plasma physics, and fusion evidence.',[74,88,89,90,91,96,105,106,107],['A public-data or model-fitting analysis with uncertainty','An explanation of significance, exclusions, and model assumptions'])
route('astro','Astronomy and the physical universe','Stellar evolution, compact objects, galaxies, cosmology, and observational inference.',[75,76,77,78,79,80,81,92,93,96,105,106,107],['An orbital or astronomical-data project with coordinate and unit checks','A model-to-observable inference notebook'])
route('interdisciplinary','Physics across complex systems','Fluids, geophysics, climate, soft matter, biophysics, and measurement methods.',[31,32,59,94,95,96,105,106,107],['A transport or stochastic-process benchmark','A critique separating prediction, mechanism, and validation'])
route('history','Newton, Einstein, and Tesla: works in context','Technical prerequisites plus all historical chapters. Use the archive guides to expand into letters, notebooks, and complete-work editions.',range(97,105),['A ten-document archival ledger with dates and editions','Three claims audited against primary sources and modern physics'])
route('research','Research methods and reproducible computation','A portable methods route. Add the specialty chapter prerequisites of every paper or project you choose.',[105,106,107,108],['A cleanly reproducible baseline','A sensitivity analysis and an independently reviewable proposal'])

projects=[]
def J(i,title,field,pre,refs,tool,question,steps,gate,deliver,extension):
    projects.append(dict(id=f'J{i:02}',title=title,field=field,chapters=[f'P{x:03}' for x in pre],resources=refs.split(),tool=tool,question=question,steps=steps.split('|'),gate=gate,deliver=deliver,extension=extension))
J(1,'Measure a model, not just a number','Foundations',[4,14,19],'nist scipy','Spreadsheet or SciPy','Can you estimate a parameter and defend its uncertainty?',
 'Choose a safe pendulum video dataset or generate synthetic timing data | Write the measurement equation and identify length and timing errors | Fit the period model and inspect residuals | Separate repeatability from calibration uncertainty | Compare small-angle and finite-amplitude predictions',
 'A unit-consistent estimate with an uncertainty budget and an explanation of the model’s domain.','Notebook, raw-data provenance, residual plot, one-page report.','Test interval coverage on repeated synthetic datasets.')
J(2,'From ODEs to a verified oscillator','Mechanics',[10,15,27],'scipy mitmech','SciPy solve_ivp · included example','How well does a numerical integrator reproduce a known damped oscillator?',
 'Derive the underdamped analytic solution | Run examples/reproduce.py --experiment oscillator | Compare numerical and analytic position | Tighten tolerances and inspect the maximum error | Explain decay of mechanical energy',
 'Recover the analytic curve and report numerical error without confusing it with physical uncertainty.','CSV, plot, metrics JSON, and annotated derivation.','Compare underdamped, critical, and overdamped regimes.')
J(3,'A solar-system laboratory','Gravity',[26,30,106],'rebound scipy','REBOUND','Which apparent orbital changes are physical and which are numerical?',
 'Start with a two-body Kepler orbit and documented units | Use REBOUND’s tutorial to add a perturbing body | Compare integrators at matched accuracy | Track energy and angular momentum drift | Change the timestep and report convergence',
 'Recover the Kepler period and distinguish bounded integration error from a physical perturbation.','Configuration, orbit plots, conservation diagnostics, reproducibility notes.','Study resonances or a restricted three-body trajectory.')
J(4,'A double pendulum without fake certainty','Nonlinear dynamics',[29,31,106],'scipy','SciPy solve_ivp','How does sensitivity to initial conditions differ from numerical error?',
 'Derive equations with a declared angle convention | Integrate nearby initial conditions | Check energy and tolerance sensitivity | Plot separation before saturation | Compare an interpretable low-amplitude baseline',
 'Demonstrate a sensitivity interval that persists under numerical refinement.','Trajectory data, tolerance study, and short methods note.','Construct a Poincaré section or compare symplectic methods.')
J(5,'Electrostatic boundary-value solver','Electrostatics',[9,11,35,46],'fenics fipy','FEniCSx or FiPy','How do boundary conditions determine the field between shaped electrodes?',
 'Solve a rectangular Laplace problem with an analytic benchmark | Reuse an official PDE tutorial | Refine the mesh and compare potential errors | Calculate fields and inspect boundary behavior | Change electrode geometry only after validating the baseline',
 'Show error reduction and state where field estimates are mesh-sensitive.','Mesh/configuration, potential and field plots, convergence table.','Add dielectric interfaces with correct continuity conditions.')
J(6,'Resonance and an energy ledger','Circuits',[37,40,41,103],'scipy tesla1892 teslatransformer','Built-in RLC tool and SciPy','How do loss and coupling limit resonant voltage magnification?',
 'Calculate resonant frequency, impedance, and quality factor | Sweep frequency and compare with the analytic response | Add a coupled second oscillator in simulation | Account for source power, stored energy, and dissipation | Compare a specific passage of the 1892 lecture with the model',
 'Demonstrate energy balance and explain why high voltage is not free energy.','Simulation-only report, response curves, historical annotation.','Study detuning and bandwidth; do not construct high-voltage equipment.')
J(7,'A rotating magnetic field','Electromechanics',[38,41,45,102],'teslamotor scipy','NumPy/SciPy','Why can polyphase excitation produce a rotating field?',
 'Write two perpendicular coil fields in quadrature | Plot the vector tip over a cycle | Introduce phase and amplitude errors | Relate field rotation to synchronous speed | Compare the idealization with the original motor patent',
 'Recover constant magnitude in the ideal case and explain the nonideal ellipse.','Vector animation or plots, equations, claim-level patent notes.','Add a simplified rotor-slip model and label empirical parameters.')
J(8,'Wave propagation with an established Maxwell solver','Computational EM',[42,44,46,106],'meep','Meep','Can a numerical wave simulation reproduce reflection and transmission?',
 'Use an official Meep dielectric-interface example | Predict normal-incidence Fresnel coefficients | Choose resolution, source bandwidth, and absorbing layers | Measure reflected and transmitted flux | Check resolution and domain-size convergence',
 'Close the energy budget within a declared numerical tolerance.','Input file, flux data, convergence plots, limitations.','Study a waveguide or photonic-crystal band gap.')
J(9,'Diffraction from aperture to data','Optics',[11,49,50],'scipy phet','SciPy FFT and built-in diffraction tool','When does the simple far-field pattern describe an aperture?',
 'Derive single-slit minima | Sample an aperture and calculate its Fourier transform | Compare numerical intensity with sinc-squared theory | Vary sample spacing and window width | Explain paraxial and far-field assumptions',
 'Recover minimum locations and document sampling and normalization.','Aperture definitions, normalized plots, error table.','Compare a circular aperture or a phase mask.')
J(10,'Heat diffusion with a known answer','Transport',[11,52,59,106],'scipy fipy','SciPy sparse solvers · included example','Does a discretized diffusion equation recover a decaying sine mode?',
 'Derive the analytic eigenmode with fixed-temperature boundaries | Run examples/reproduce.py --experiment diffusion | Compare profiles and decay factors | Refine the spatial grid | State boundary conditions and diffusivity units',
 'Show a bounded error and explain spatial discretization versus time propagation.','CSV, figure, metrics JSON, derivation.','Move to FiPy for a composite medium or two-dimensional geometry.')
J(11,'Entropy and finite-size effects','Statistical physics',[13,56,58,106],'lammps tongstatfield','LAMMPS examples or an explicitly small lattice model','Which signatures of a transition survive finite size and sampling?',
 'Choose a documented simple model and equilibrium ensemble | Reproduce a tutorial observable | Estimate autocorrelation and effective sample size | Repeat at several system sizes | Separate finite-size trends from a thermodynamic-limit claim',
 'Report sampling uncertainty and a finite-size limitation for every claimed trend.','Input decks, seeds, observable curves, uncertainty discussion.','Compare heating and cooling protocols without assuming equilibrium.')
J(12,'A quantum eigenproblem with convergence','Quantum mechanics',[7,11,63,106],'scipy mitqm','SciPy eigh_tridiagonal · included example','Does a discretized Hamiltonian recover infinite-well energies?',
 'Derive the analytic spectrum | Run examples/reproduce.py --experiment well | Compare the first three eigenvalues over multiple grids | Normalize eigenvectors in the continuum convention | Measure the convergence rate',
 'Recover the expected spectrum and approximately second-order spatial convergence.','Energies CSV, wavefunction plot, metrics JSON, normalization explanation.','Replace the well by a finite well and compare bound-state counts.')
J(13,'Coherence, relaxation, and a density matrix','Open quantum systems',[61,65,70],'qutip','QuTiP','Can you distinguish coherent oscillation, dephasing, and relaxation?',
 'Reproduce an official two-level dynamics example | Solve a closed-system baseline | Add separate dephasing and relaxation channels | Track trace, positivity, and Bloch components | Compare characteristic times with analytic limits',
 'Explain each dissipator and verify a physical normalized state.','Environment file, notebook, state trajectories, parameter table.','Use a driven cavity model after checking Hilbert-space truncation.')
J(14,'Bell correlations and what they imply','Quantum foundations',[13,65,69],'qutip preskill epr','QuTiP or exact NumPy state vectors','How does a singlet violate CHSH while respecting no-signalling?',
 'Derive the local bound with explicit assumptions | Calculate ideal singlet correlations | Choose measurement angles and compute CHSH | Add depolarizing noise and sampling fluctuations | Check each party’s marginal distribution',
 'Report a violation under declared assumptions and demonstrate unchanged remote marginals.','Correlation table, noise curve, EPR-versus-Bell explanation.','Study detection or setting-choice assumptions without claiming a loophole-free simulation.')
J(15,'Quantum error correction from a small code','Quantum information',[72,73,106],'qiskit ibmlearn preskill','Qiskit Aer or documented simulator','How do physical errors become syndromes and logical failures?',
 'Implement a documented small stabilizer-code tutorial | Verify noiseless stabilizers and logical states | Inject one correctable error at a time | Compare decoding success under a stated noise model | Relate the toy code to one selected recent QEC paper',
 'Separate physical error rate, syndrome accuracy, and logical error probability.','Circuit, seed and noise configuration, logical-error plot.','Compare a second decoder or noise model; do not extrapolate a toy result to hardware scalability.')
J(16,'Geodesics and invariant checks','General relativity',[17,77,79,106],'sympy scipy tonggr','SymPy plus SciPy','Can a geodesic calculation preserve its conserved quantities?',
 'Declare the metric and units | Obtain symbolic connection coefficients | Integrate a simple exterior geodesic | Monitor normalization and conserved energy/angular momentum | Compare a weak-field orbit with Newtonian behavior',
 'Report invariants and identify coordinate singularities separately from curvature.','Symbolic notebook, trajectory, conservation and convergence plots.','Compare null and timelike trajectories or different coordinate charts.')
J(17,'Reproduce a public gravitational-wave tutorial','Gravitational waves',[11,14,80,107],'gwosc scipy','GWOSC tutorials and scientific Python','What evidence in public strain data supports a documented event analysis?',
 'Choose an official GWOSC event tutorial and record dataset version | Reproduce its preprocessing and units | Compare time-domain and frequency-domain views | Inspect background/noise assumptions | Reproduce one published tutorial figure with all changes recorded',
 'Explain the effect of filtering and avoid interpreting every transient as a source.','Data provenance, notebook, reproduced figure, limitations.','Study a second event or a documented parameter-estimation tutorial.')
J(18,'Cosmological distances and model dependence','Cosmology',[14,81,107],'astropy tongcosmo','Astropy cosmology','How do expansion assumptions change a distance–redshift relation?',
 'Derive the distance integral for a declared FLRW model | Calculate it with Astropy | Compare a low-redshift limit | Vary one cosmological parameter at a time | Relate the calculation to BAO observables in the DESI paper',
 'Distinguish a model sensitivity plot from a fit to actual survey likelihoods.','Notebook, distance curves, parameter assumptions, reading worksheet.','Use an official released likelihood only after documenting its covariance and selection.')
J(19,'A converged electronic-structure calculation','Materials',[83,84,87,106],'qe','Quantum ESPRESSO','How much of a band-structure result depends on numerical settings?',
 'Reproduce a small official tutorial material | Record pseudopotential provenance and functional | Converge cutoff and k-point sampling | Calculate a band or density-of-states plot | Separate numerical convergence from model accuracy',
 'Provide a convergence table and identify the approximation’s limitations.','Input files, environment and potential references, energies, band plot.','Compare a second functional or structure without claiming experiment-level agreement by default.')
J(20,'Quantum transport in a small device','Mesoscopic physics',[63,83,86],'kwant','Kwant','How do channels and disorder affect transmission in a tight-binding model?',
 'Run a documented Kwant wire tutorial | Verify the clean-system channel steps | Add controlled disorder with recorded seeds | Average over realizations with error bars | Examine finite-size and lead assumptions',
 'Explain transmission units and distinguish model conductance from a fabricated-device prediction.','Model code, disorder ensemble, transmission curves.','Explore magnetic-field or edge-state examples using matched model assumptions.')
J(21,'Particle data and a defensible fit','Particle physics',[14,88,96,107],'cern scikithep','CERN Open Data and Scikit-HEP','Can you reproduce a simple public invariant-mass analysis?',
 'Choose an official educational open-data example | Document event selection and units | Reconstruct the indicated invariant mass | Compare data with a declared background model | Inspect binning and systematic sensitivity',
 'Reproduce an expected feature and state why a plot alone does not establish a new particle.','Data identifiers, analysis script, cutflow, fit and uncertainty note.','Compare an unbinned fit or alternate background model with a declared protocol.')
J(22,'Nuclear transport as a convergence study','Nuclear physics',[13,90,106],'openmc','OpenMC','How do Monte Carlo histories control the uncertainty of a transport estimate?',
 'Choose a documented educational shielding benchmark | Identify cross-section data and boundary conditions | Run several particle-history counts | Compare reported uncertainty and repeated-run variability | Record modeling and nuclear-data limitations',
 'Distinguish stochastic uncertainty from uncertain physical inputs; use published educational geometries.','Input files, cross-section provenance, convergence curves.','Study a non-operational sensitivity exercise on material thickness.')
J(23,'Plasma scales before fusion claims','Plasma physics',[38,55,91],'plasmapy plasmatext','PlasmaPy','Which dimensionless ratios tell you whether a plasma approximation is plausible?',
 'Use unit-aware PlasmaPy particle and plasma calculations | Compute Debye length, gyrofrequency, and characteristic collision scales | Compare scales with a stated model geometry | Audit an MHD-versus-kinetic assumption | Read the LM26 or heat-conduction paper with these checks',
 'Justify a regime classification and separate heating, confinement, fusion yield, and net-energy statements.','Scale table, code, regime diagram, paper worksheet.','Use an official plasma simulation tutorial only after stating its closure assumptions.')
J(24,'A model of a star or a galaxy observation','Astrophysics',[55,79,92,93],'astropy scipy','Astropy and SciPy','Can a simple physical model be connected to an observable?',
 'Choose a stellar-structure toy model or public photometry tutorial | State units, coordinates, and assumptions | Reproduce an analytic or official tutorial baseline | Propagate measurement or input uncertainty | Explain the degeneracy between physical parameters',
 'Separate inferred quantities from direct observations and report model sensitivity.','Notebook, data provenance, plot, uncertainty interpretation.','Compare two plausible models using the same observations.')
J(25,'Turbulence and climate: test the baseline','Fluids and climate',[31,32,94,106,107],'scipy fipy','SciPy or FiPy','Does a proposed predictor improve on a simple physical or statistical baseline?',
 'Choose an accessible documented flow or climate benchmark | Define train/test separation before fitting | Build persistence and simple physical baselines | Evaluate error by regime and lead time | Test a distribution shift and report failures',
 'Prevent data leakage and distinguish predictive skill from a demonstrated physical mechanism.','Dataset ledger, split definitions, baseline comparison, error analysis.','Replicate one figure from a selected recent benchmark paper if its data and code are accessible.')
J(26,'Soft matter and stochastic inference','Biophysics',[13,55,59,95,107],'scipy lammps','SciPy or LAMMPS','Can you infer diffusion or elasticity without hiding finite-sample effects?',
 'Start with a Brownian-particle or documented polymer model | Compare an analytic mean-square displacement or elastic limit | Fit over multiple observation windows | Estimate correlated-sample uncertainty | Compare a recent soft-matter paper’s regime with your toy model',
 'Explain finite-window bias and why an idealized model is not a full cell or organism.','Simulation settings, fitted parameters, coverage or sensitivity plot.','Introduce viscoelasticity only after validating the Newtonian or elastic baseline.')
J(27,'Three scientists, three evidence audits','History',[97,99,103,104],'newton einstein eincatalog tesla teslapatents','Primary-source ledger','What survives when a famous claim is checked against a dated primary source?',
 'Choose one Newton proposition, one Einstein paper, and one Tesla patent | Record edition, date, language, and stable identifier | Separate exact claim from later retelling | Reconstruct one calculation or conceptual argument | State modern support, limits, and remaining access gaps',
 'Every historical claim is traceable; missing documents and translation uncertainty remain visible.','Ten-record bibliography and three illustrated claim audits.','Expand into correspondence, drafts, and reception without conflating them with final publications.')
J(28,'A small, publishable-quality replication package','Research',[105,106,107,108],'arxivapi missing','Use the original project’s open-source stack','Can another person reproduce one figure and understand a meaningful extension?',
 'Choose one tractable paper after checking data, code, and license | Freeze a baseline with exact configuration and hardware | Reproduce one central figure or document the discrepancy | Vary one justified assumption with matched evaluation | Write a concise methods report and invite technical criticism',
 'A clean rerun, an honest comparison, and a falsifiable extension; publication is not guaranteed.','Repository, environment, data instructions, figures, limitations, proposal.','Contribute a tested fix or tutorial upstream after checking the project’s contribution policy.')

pioneers=[]
def contribution(title,date,claim,evidence,modern,refs):
    return dict(title=title,date=date,claim=claim,evidence=evidence,modern=modern,resources=refs.split())
def corpus(rid,coverage,access=None):
    r=next(x for x in resources if x['id']==rid)
    return dict(title=r['title'],url=r['url'],coverage=coverage,access=access or r['access'])
pioneers.append(dict(id='newton',name='Isaac Newton',dates='1642/43–1727',intro='Study Newton through mathematical arguments, experiments, revisions, and the much wider manuscript record. Historical dates can use different calendar conventions; preserve the edition’s date and explain conversions.',chapters=['P097','P098','P104'],contributions=[
 contribution('Mathematical principles of motion and gravitation','1687; revised 1713 and 1726','A unified mathematical treatment links terrestrial and celestial motion through laws of motion and universal gravitation.','Principia definitions, propositions, phenomena, and later revisions.','A central low-speed, weak-field approximation within modern mechanics and gravitation.','principia newton'),
 contribution('Experimental optics and the nature of white light','Opticks, 1704 and later editions','Prism experiments distinguish refrangibility and investigate the composition of white light.','Experiment descriptions and arguments in Opticks; later Queries have a different evidential role.','Modern wave and quantum optics explain more phenomena; do not read every historical hypothesis as current theory.','opticks'),
 contribution('Fluxions, series, and mathematical notebooks','Principally 1660s onward','Newton developed calculus-related methods and extensive work on series and geometry.','Dated notebook material, scholarly transcriptions, and publication history.','Use modern calculus notation while preserving the distinction between private development, publication, and the work of Leibniz and others.','waste newton'),
 contribution('The wider surviving record','Lifetime manuscripts and correspondence','The corpus includes theology, chronology, alchemy, administration, and correspondence as well as science.','Multiple custodial archives and scholarly editions with different coverage.','These documents are essential to historical study but do not all represent validated physics.','newton chymistry newtonnli')],corpus=[corpus('newton','Ongoing scholarly edition across scientific and non-scientific writings; not a completed universal corpus.'),corpus('principia','Cambridge annotated first-edition facsimile; direct access was restricted during checking.'),corpus('opticks','Linked Book I section; follow the edition’s continuations for the rest of the book.'),corpus('waste','Notebook facsimile and manuscript context; access may vary.'),corpus('chymistry','Specialist alchemical manuscript edition.'),corpus('newtonnli','Custodial gateway for additional manuscripts.')],reading=['Read modern mechanics and geometric tools first (P019–P030).','Read the Principia definitions and laws, then one Book I proposition and its Book III application.','Study a specific Opticks experiment before reading the speculative Queries.','Compare a notebook draft with a later published argument.','Expand systematically using a document ledger, including non-scientific works and inaccessible items.'],myths=[dict(claim='Newton alone invented every part of classical science.',assessment='His achievements drew on predecessors and coexisted with other major developments; preserve attribution and the history of publication.'),dict(claim='An online Newton edition already contains every surviving work.',assessment='The editorial mission is comprehensive, but digitization, transcription, and access remain uneven.')]))
pioneers.append(dict(id='einstein',name='Albert Einstein',dates='1879–1955',intro='Follow separate investigations in light, matter, spacetime, statistics, and quantum foundations, then explore the later correspondence and unfinished unification programs. The collected edition and digitized archive are still incomplete.',chapters=['P099','P100','P101','P104'],contributions=[
 contribution('The 1905 investigations','1905','Light quanta, Brownian motion, special relativity, and mass–energy address different problems; the dissertation and other work also belong to the year.','Original papers and the Library of Congress reading guide.','Re-derive each claim using its own assumptions and distinguish later textbook formulations.','ein1905 einlight einbrown einsr einmass'),
 contribution('General relativity and cosmology','1915 field equations; 1916 exposition; 1917 cosmology','Gravity is described through spacetime geometry; cosmological modeling adds explicit assumptions about the universe.','Technical exposition, original cosmology paper, and the collected archive.','GR has extensive experimental support; dark matter, dark energy, singularities, and quantum gravity remain distinct open questions.','eingr eincosmo einstein'),
 contribution('Quantum radiation and quantum gases','1917; 1924–1925','Radiation coefficients describe absorption and emission; Bose–Einstein statistics imply new behavior in an ideal gas.','Radiation paper record and the preserved ideal-gas manuscript.','Credit Bose’s antecedent contribution; stimulated emission is not the same as building a laser, and a condensation prediction precedes experimental realization.','einradiation einbose'),
 contribution('Quantum completeness and correlations','1935 and related correspondence','Einstein, Podolsky, and Rosen questioned completeness using correlated variables and explicit assumptions.','Original EPR paper, later correspondence, and modern Bell theory as a separate development.','Modern entanglement does not allow controllable faster-than-light communication.','epr eincatalog'),
 contribution('Later research, collaborators, and unfinished programs','1920s–1955','The archive includes unification attempts, criticism, collaborations, and a broad correspondence beyond the famous papers.','Published volume descriptions and archival catalogue records; coverage varies by year and item.','These attempts are historically valuable without constituting a completed experimentally validated unified theory.','ein17 eincatalog')],corpus=[corpus('einstein','Authoritative edition status and gateways; publication program remains ongoing.'),corpus('einportal','Publisher landing page announces a September 30 launch and initial 16-volume coverage through 1930.','Checked 7 September 2026; do not assume the announced portal is already open or freely complete.'),corpus('ein17','Volume 17 covers June 1929–November 1930, beyond the initial portal coverage description.'),corpus('eincatalog','Temporary archive catalogue; many records, only a subset digitized.'),corpus('einbook','Accessible general-audience book; not a substitute for the technical papers.'),corpus('ein1905','Guide to the famous papers with links whose access varies.')],reading=['Begin with modern special relativity, elementary quantum physics, and Einstein’s accessible relativity book.','Read the four famous 1905 papers as independent investigations; add the dissertation to your ledger.','Study differential geometry before the 1916 GR exposition and 1917 cosmological paper.','Read radiation, Bose-gas, and EPR work with modern statistical and quantum mechanics.','Extend chronologically through edited volumes and the archive, recording unavailable or untranslated items.'],myths=[dict(claim='The four 1905 papers are Einstein’s entire scientific work.',assessment='They are a famous selection from a much larger scientific and documentary corpus.'),dict(claim='The old Princeton archive URL guarantees free access to every work.',assessment='It now routes to a changed publisher offering with announced coverage and access arrangements; check the current page.'),dict(claim='Einstein proved entanglement sends usable information faster than light.',assessment='EPR concerned completeness and locality assumptions; quantum correlations do not enable controllable superluminal signaling.')]))
pioneers.append(dict(id='tesla',name='Nikola Tesla',dates='1856–1943',intro='Study Tesla as an inventor and electrical engineer through granted patent claims, preserved lectures, apparatus descriptions, and archival records. Evaluate each performance claim separately from later popular stories.',chapters=['P102','P103','P104'],contributions=[
 contribution('Polyphase systems and rotating magnetic fields','US381968A, granted 1888','Phased currents produce shifting magnetic poles in the described motor arrangement.','Original motor specification and claims; historical system context.','Explain the field geometry, rotor induction, and system losses without assigning all AC technology to Tesla.','teslamotor teslapatents'),
 contribution('High-frequency electrical experiments and transformers','1892 lecture; US593138A, 1897','Investigations and devices explore high-frequency currents, resonant behavior, and transformer arrangements.','Preserved lecture and individually identified transformer patent.','Distributed fields, loss, resonance, and breakdown require modern modeling; use simulations for this course.','tesla1892 teslatransformer'),
 contribution('Remote control','US613809A, granted 1898','A receiver and control arrangement direct a moving vessel.','Original patent describes the command, switching, and actuation system.','Teleoperation is a predecessor to remote-control engineering; it is not equivalent to modern autonomous artificial intelligence.','teslacontrol'),
 contribution('Wireless transmission ambitions','US645576A, 1900; Wardenclyffe project','Proposes transmission through natural media and ambitious communication or energy systems.','Patent specification and site-custodian history of the unfinished project.','Wireless transfer is physically possible within defined coupling and loss limits; a patent is not proof of worldwide efficient power distribution.','teslapower wardenclyffe'),
 contribution('Disk turbine and wider technical writings','US1061206A, granted 1913; other publications','A disk turbine transfers momentum through fluid interaction; the broader archive includes additional apparatus and investigations.','Original turbine patent plus museum writings, patent, and archive indexes.','Assess efficiency for specified operating conditions; do not infer universal superiority from the existence of a patent.','teslaturbine teslawritings')],corpus=[corpus('tesla','Museum archive of notes, drawings, calculations, correspondence, and legal documents; not a fully digitized public corpus.'),corpus('teslapatents','Navigate exact patent numbers and national equivalents; aggregate counts use different definitions.'),corpus('teslalectures','Dated lecture inventory; some manuscripts are lost or incomplete.'),corpus('teslawritings','Publication and writing index; follow individual records for readable texts.'),corpus('tesla1892','One preserved lecture available as a public-domain-in-USA text.'),corpus('wardenclyffe','Site history of an unfinished undertaking, not a performance validation.')],reading=['Learn electrostatics, magnetism, circuits, Maxwell waves, and machinery before technical patent interpretation.','Read US381968A and derive the ideal rotating field.','Read the 1892 lecture with a simulation of lossy resonance.','Compare remote-control, transmission, and turbine patents claim by claim.','Expand into letters, laboratory notes, lighting and X-ray investigations, and autobiographical writings through the museum indexes.'],myths=[dict(claim='Tesla discovered unlimited energy from nothing.',assessment='Resonance and wireless coupling redistribute or transfer supplied energy; they do not violate energy conservation.'),dict(claim='A patent establishes that every described system achieved its advertised performance.',assessment='A granted specification and a reproducible performance demonstration are different kinds of evidence.'),dict(claim='The archive’s document count is Tesla’s number of inventions.',assessment='Call numbers and archival units are not invention counts or guarantees of downloadable full text.')]))

advisor={'html': '''
<p class="lead">Learn one idea, derive one result, test one prediction, and leave an artifact someone else can inspect.</p>
<h2>Choose your first route</h2>
<p>If fractions, rearranging equations, graphs, or vectors feel uncertain, start at P001. If those are comfortable, attempt the exit gates before skipping ahead. A checked chapter records your own assessment; it is not an exam credential. The foundation route leads into mechanics. Chapter IDs are stable references; the displayed order introduces measurement and mechanics early and adds advanced mathematics as needed. Quantum mechanics needs linear algebra, differential equations, probability, and waves. General relativity needs special relativity, multivariable calculus, tensors, and differential geometry. Electromagnetic engineering needs vector calculus, circuits, and wave theory.</p>
<h2>A realistic weekly cycle</h2>
<p>At eight hours per week, try three hours of reading or lectures, three hours of problems and derivations, one hour of computation or data work, and one hour of retrieval practice and notes. Study one main chapter at a time. Keep a short mathematics repair session alongside it. Every four weeks, repeat an old derivation without notes and improve one earlier project.</p>
<p>Chapter hours are planning estimates for reading, selected exercises, and a small artifact. They are not measured completion times or research-readiness guarantees. The combined route is a multi-year reference program. Advanced mastery, full textbook exercise sets, major projects, and original research require additional time. Use the path estimates to choose a manageable specialty.</p>
<h2>How to use a chapter</h2>
<ol><li>Check its prerequisites and draw a physical diagram before manipulating equations.</li><li>Read the named source’s relevant section using the subchapter topic terms. Prefer one main textbook and one lecture sequence rather than collecting many parallel courses.</li><li>Work each practice task; keep units, sign conventions, and limiting cases visible.</li><li>Complete the derivation and exercise, then use a calculator or an established solver to test the result.</li><li>Explain the exit gate aloud and write what would make the model fail. Save a plot, derivation, or uncertainty table before marking completion.</li></ol>
<h2>Books, lectures, and software</h2>
<p>OpenStax supplies the beginner spine; MIT OpenCourseWare provides full lecture and problem sequences; the Feynman Lectures provide complementary explanations; David Tong’s notes connect undergraduate foundations to advanced theory. Course links indicate where books, notes, assignments, or videos can be found, but not every course includes every format. IBM and Preskill support the quantum-information route. Use official examples for scientific packages and check their current installation instructions and licenses.</p>
<p>The built-in tools are small explanatory calculations. The optional included SciPy examples solve three textbook benchmarks using established numerical algorithms. For full PDE, many-body, atomistic, quantum-open-system, or astronomy workflows, follow the projects using Meep, FEniCSx, FiPy, QuTiP, Quantum ESPRESSO, LAMMPS, REBOUND, Astropy, or the cited alternative. Basic study needs a laptop. Large materials, field, or HPC projects may need substantial memory or institutional computing; validate a small case before scaling.</p>
<h2>What the research desk covers</h2>
<p>The curated snapshot was checked on 7 September 2026. Its 25 papers are representative entry points, including recent preprints and selected peer-reviewed anchors, rather than a systematic census of every field. Annotations are source-based triage of methods, claims, and limitations; they do not certify an independent reproduction of the full paper. First-submission, update, and journal dates describe different events.</p>
<p>Manual discovery queries arXiv for eight newest submitted records in one selected category. Results can be cached, delayed, cross-listed, revised, or temporarily unavailable. This does not cover every journal, archive, language, or subfield; newest submission is not newest important result. A journal reference in a feed is author-supplied metadata until checked against the journal. Inspect version history, DOI, publisher status, errata, source code, and data before relying on a claim.</p>
<p>Use the paper worksheet to record the question, assumptions, method, central figure, uncertainty, strongest supported conclusion, missing evidence, and a replication plan. Follow the references into earlier foundations. A null result, bound, simulation, instrument proposal, and experimental detection answer different questions.</p>
<h2>Established physics and open questions</h2>
<p>Quantum mechanics, classical electromagnetism, thermodynamics, and general relativity have substantial empirical foundations within tested regimes. The interpretation of quantum mechanics, quantum gravity, dark-sector explanations, many-body phases, and nonequilibrium phenomena contain open or actively contested questions. The roadmap teaches the accepted mathematical tools before speculative extensions. A recent paper is a starting point for evaluation, not a reason to discard a well-tested theory.</p>
<h2>Reading Newton, Einstein, and Tesla</h2>
<p>The historical guides map major scientific works and provide routes into letters, drafts, notebooks, patents, and other writings. They do not reproduce or claim to exhaust the entire surviving corpora. Record document identifier, date, edition, translator, archive, page or folio, and access status. Separate an original author’s claim, an editor’s interpretation, and your modern assessment. Some material is unavailable, paywalled, untranslated, lost, or not digitized. A patent is a claim-bearing technical document, not an automatic certificate of measured performance.</p>
<h2>Milestones and advisor checkpoints</h2>
<ul><li><strong>Foundation:</strong> solve a mechanics problem with units and an uncertainty estimate; reproduce an analytic curve numerically.</li><li><strong>Intermediate:</strong> solve a boundary-value or eigenvalue problem; explain the relevant symmetry or conservation law.</li><li><strong>Specialty:</strong> reproduce an official software tutorial and test convergence, sampling, or calibration.</li><li><strong>Research:</strong> reproduce one paper figure, document discrepancies, and propose one falsifiable extension. Ask a knowledgeable instructor or researcher to critique it.</li></ul>
<p>This advisor is an authored study guide, not a connected AI tutor. There are no paid model calls or automatic claims of personalized scientific review.</p>
<h2>Local tools and notebooks</h2>
<p>The website’s content and calculators work offline after download. Progress, chapter notes, and paper worksheets stay in this browser’s storage; use Export backup regularly and before switching devices or clearing browser data. Import replaces the current notebook after confirmation. Live paper discovery uses the hosted service when opened as a private Site, or the supplied server in the downloadable localhost edition. It needs internet access. Source sites open externally. The hosted edition uses Sites access controls; the localhost edition needs no account.</p>
<p>Calculator constants use the 2022 CODATA adjustment with exact SI defining constants where applicable. Visible formulas, assumptions, units, and numerical checks matter more than displayed decimal length; calculator output is not automatically an uncertainty estimate. High-voltage Tesla apparatus, high-power lasers, ionizing radiation, pressure systems, and fusion devices are represented by reading and simulation projects, not home construction instructions.</p>
'''}
