"""Dedicated subject rooms. Original learning plans; linked sources remain with their owners."""

# Source-specific access notes prevent free viewing from implying redistribution rights.
R('mitwaves','MIT 8.03SC · Vibrations and Waves','MIT OpenCourseWare','https://ocw.mit.edu/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/','Course + video','Work through oscillations, coupled modes, mechanical waves, sound, and optics with lecture videos and problem sets.','Fall 2016','Free OpenCourseWare')
R('russell','Acoustics and Vibration Animations','Daniel A. Russell / Penn State','https://www.acs.psu.edu/drussell/demos.html','Demonstrations','Compare longitudinal waves, standing modes, radiation, and vibrating structures.','Living university collection','Free viewing','Linked demonstrations are not bundled or relicensed.')
R('audacity','Audacity · official FAQ','Audacity project','https://www.audacityteam.org/faq/','Open-source tool','Record and inspect waveforms and spectra; preserve original recordings and record all processing.','Living documentation','Free open-source software','Use modest, comfortable listening levels; a microphone recording is not an absolute sound-level calibration.')
R('signals','SciPy signal processing tutorial','SciPy community','https://docs.scipy.org/doc/scipy/tutorial/signal.html','Open-source tool','Filtering, spectral representations, windowing, and power spectral density units.')
R('fft','SciPy Fourier transforms tutorial','SciPy community','https://docs.scipy.org/doc/scipy/tutorial/fft.html','Open-source tool','Discrete transforms, frequency axes, normalization, and inverse checks.')
R('chladni','Chladni Plates','Harvard Natural Sciences Lecture Demonstrations','https://sciencedemonstrations.fas.harvard.edu/presentations/chladni-plates','Demonstration','Observe nodal patterns and the effects of plate support and excitation.','Undated; checked 2026-09-07','Free demonstration description','A plate mode depends on material, geometry, and boundary conditions; it is not evidence of a healing frequency.')
R('symgeometry','SymPy geometry module','SymPy community','https://docs.sympy.org/latest/modules/geometry/index.html','Open-source tool','Check intersections, distances, polygons, circles, and exact symbolic constructions.')
R('euclid','Euclid’s Elements · online edition','David E. Joyce / Clark University','https://aleph0.clarku.edu/~djoyce/java/elements/elements.html','Book / historical edition','Read definitions and propositions; start at Book I, then similarity and regular solids.','Edition begun 1996; ancient work c. 300 BCE','Free university text','Indexed university edition; direct access was intermittent during research. Legacy Java diagrams may not run.')
R('geometries','How Many Geometries Are There?','Alan Beardon / Cambridge NRICH','https://nrich.maths.org/articles/how-many-geometries-are-there','Teaching article','Compare Euclidean assumptions with great circles and spherical triangles.','1 February 2011','Free reading')
R('mitgeometry','MIT 18.950 · Differential Geometry','Paul Seidel / MIT','https://ocw.mit.edu/courses/18-950-differential-geometry-fall-2008/pages/syllabus/','Course / notes','Curves, hypersurfaces, curvature, lengths, and distances after multivariable calculus and linear algebra.','Fall 2008','Free OpenCourseWare')
R('goldenmyths','Myths of maths: The golden ratio','Chris Budd / Cambridge Plus','https://plus.maths.org/myths-maths-golden-ratio','Scholarly explanation','Distinguish exact ratios, particular natural examples, and selective visual overlays.','23 February 2020','Free reading')
R('metpatterns','Islamic Art and Geometric Design: Activities for Learning','The Metropolitan Museum of Art','https://www.metmuseum.org/met-publications/islamic-art-and-geometric-design-activities-for-learning','Book + activities','Use grids, repeats, and museum objects for culturally situated geometric constructions.','2004; 46 pages','Free PDF','Check the publication’s reuse terms; a shared geometry does not imply a shared spiritual meaning.')
R('mandala','Mandala','Rubin Museum of Himalayan Art','https://rubinmuseum.org/highlights/mandala/','Museum interpretation','Study named Buddhist objects and the roles of visualization, cosmology, and ritual.','Undated; checked 2026-09-07','Free reading','Examples span distinct places and dates; a museum explanation is not a physics claim.')
R('yantra','Yantra · 1940,0716.329','British Museum','https://www.britishmuseum.org/collection/object/A_1940-0716-329','Museum object record','Study an eighteenth-century northern Indian metal ritual plaque with mantras.','Object: 18th century','Public catalogue','Identification and description checked in the museum search index; full page fetch failed. This record does not identify every yantra with the Sri Yantra.')
R('keplersolids','Johannes Kepler’s Mysterium Cosmographicum','Karl Galle / Thinking 3D','https://www.thinking3d.ac.uk/Kepler1596/','History of science','Examine the 1596 nested-solid model and linked ETH-Bibliothek book images.','8 January 2018; book 1596','Free scholarly explanation','A historical model, superseded as an account of planetary spacing.')
R('pacioli','Divina proportione','Luca Pacioli / Metropolitan Museum of Art','https://www.metmuseum.org/art/collection/search/336656','Primary-work object record','Inspect the 1509 book and illustrations after Leonardo da Vinci.','1 June 1509','Public catalogue; displayed images marked public domain','The book does not establish hidden golden-ratio grids in Leonardo’s paintings.')
R('mandorla','Tabernacle frame','The Metropolitan Museum of Art','https://www.metmuseum.org/art/collection/search/460332','Museum object record','Read the catalogue’s identification of a mandorla around the Crucifixion.','Object: c. 1406','Public catalogue','Historical iconography does not establish one exact equal-circle construction for every mandorla.')
R('astronomybook','Astronomy 2e','OpenStax / Rice','https://openstax.org/books/astronomy-2e/pages/preface','Book','Begin with sky observations and instruments; continue through stars, galaxies, and cosmology.','2022 edition','Open textbook')
R('mitastro','MIT 8.282J · Introduction to Astronomy','MIT OpenCourseWare','https://ocw.mit.edu/courses/8-282j-introduction-to-astronomy-spring-2006/','Course','Quantitative astronomy of the Solar System, stars, interstellar material, galaxies, and universe.','Spring 2006','Free OpenCourseWare')
R('nasaems','Tour of the Electromagnetic Spectrum','NASA Science','https://science.nasa.gov/ems/','Guide + video','Relate wavelength bands to instruments and astronomical information.')
R('sonification','Data Sonifications','NASA Science','https://science.nasa.gov/science-research/astrophysics/data-sonifications/','Data interpretation','Ask which measured quantity is mapped to pitch, loudness, or time; sonification is a chosen representation.')
R('perseussound','Perseus Cluster · sound','Chandra X-ray Center','https://chandra.si.edu/sound/perseus.html','Observational explanation','Compare pressure waves inferred in cluster gas with an audible-frequency rendering.','Checked 2026-09-07','Free reading','Distinguish an acoustic wave in matter from arbitrary musical mapping of electromagnetic data.')
R('stellarium','Stellarium','Stellarium project','https://stellarium.org/','Open-source tool','Plan sky observations by location, date, and time with a free desktop planetarium.')
R('lightkurve','Lightkurve tutorials','Lightkurve community','https://lightkurve.github.io/lightkurve/tutorials/','Open-source tool + notebooks','Reuse Kepler and TESS tutorials for light-curve cleaning, transit searches, and validation.')
R('transitlab','Identifying transiting planet signals','Lightkurve community','https://lightkurve.github.io/lightkurve/tutorials/3-science-examples/exoplanets-identifying-transiting-planet-signals.html','Replication tutorial','Reproduce the documented box least squares transit-search example and inspect false-positive possibilities.')
R('gaia','Gaia data access','ESA / Gaia','https://www.cosmos.esa.int/web/gaia/data-access','Open data','Choose an explicit archive release and document astrometric quality cuts; compare uncertainty-aware distance estimates.')
R('newtonreligion','Newton’s Religious Life and Work','Robert Iliffe / Newton Project','https://www.newtonproject.ox.ac.uk/view/contexts/CNTX00001','Scholarly interpretation','Study theology, anti-Trinitarian views, restoration of ancient knowledge, and the limits of a single unifying interpretation.','2013','Free reading')
R('newton2060','Prophecy fragments · Yahuda MS 7.3g','Isaac Newton / Newton Project','https://www.newtonproject.ox.ac.uk/view/texts/normalized/THEM00437','Primary manuscript transcription','Read folio 13v: the 1,260-year calculation from AD 800 and Newton’s qualification of the resulting 2060 date.','Post-1700; catalogue dating','Free scholarly transcription','A possible lower bound in one prophetic interpretation, not a prediction of the world’s destruction.')
R('newtontemple','Solomon’s Temple and sacred-cubit drafts','Isaac Newton / Newton Project','https://www.newtonproject.ox.ac.uk/view/translation/TRAN00004','Primary manuscript translation','Follow textual reconstruction and comparison of ancient units in Yahuda MS 2.4.','Drafts 1680s–1690s; translation December 2013','Free scholarly translation','Michael Silverthorne translation. Reported measurements are historical evidence, not precise modern surveys.')
R('newtonchronology','The Chronology of Ancient Kingdoms Amended','Isaac Newton / Newton Project','https://www.newtonproject.ox.ac.uk/catalogue/record/THEM00183','Primary-work edition','Follow the linked chapters and compare historical reconstruction with modern source criticism.','1728; posthumous','Free scholarly edition')
R('vivekananda','Letter to E. T. Sturdy · 13 February 1896','Swami Vivekananda / Complete Works, vol. 5','https://en.wikisource.org/wiki/The_Complete_Works_of_Swami_Vivekananda/Volume_5/Epistles_-_First_Series/LVII_Blessed_and_Beloved','Primary correspondence reproduction','Read Vivekananda’s report of meeting Tesla and the prospective mathematical demonstration.','13 February 1896','Free transcription','Wikisource reproduction; manuscript facsimile not independently checked. The anticipated demonstration is not a documented completed proof.')
R('teslahuman','The Problem of Increasing Human Energy','Nikola Tesla / The Century Magazine','https://teslauniverse.com/nikola-tesla/articles/problem-increasing-human-energy','Primary article reproduction','Compare engineering discussion with mechanical analogies for human progress and philosophical reflections.','June 1900, pp. 175–211','Free transcription at Tesla Universe','Publication metadata and transcription checked; original periodical facsimile not independently verified.')
R('teslaplanets','Talking with the Planets','Nikola Tesla / Collier’s Weekly','https://teslauniverse.com/nikola-tesla/articles/talking-planets','Primary article reproduction','Separate observed electrical disturbances from Tesla’s later speculation about intelligent signals.','9 February 1901, pp. 4–5','Free transcription at Tesla Universe','Distinguish the editorial introduction from Tesla’s own words; extraterrestrial contact was not established.')
R('teslamemoir','My Inventions I · My Early Life','Nikola Tesla / Electrical Experimenter','https://teslauniverse.com/nikola-tesla/articles/my-inventions-i-my-early-life','Primary autobiographical reproduction','Read Tesla’s retrospective accounts of vivid images, mental invention, counting, and multiples-of-three habits.','February 1919, pp. 696–697, 743–747','Free transcription at Tesla Universe','Self-reports do not establish psychic powers, a diagnosis, or a 3–6–9 theory. Original periodical facsimile not independently verified.')
R('teslaether','Experiments with Alternate Currents of Very High Frequency','Nikola Tesla / AIEE lecture','https://teslauniverse.com/nikola-tesla/lectures/experiments-alternate-currents-very-high-frequency-and-their-application','Primary lecture reproduction','Study the mechanical ether language of Tesla’s electrical work before his 1896 meeting with Vivekananda.','20 May 1891, Columbia College, New York','Free transcription at Tesla Universe','Historical physical hypothesis; do not equate ether with a demonstrated modern quantum-vacuum mechanism.')

def L(title, topics, practice):
    return dict(title=title,topics=topics.split(' | '),practice=practice)
def M(title, idea, lessons, gate, refs):
    return dict(title=title,idea=idea,lessons=lessons,gate=gate,resources=refs.split())
def J(title, question, steps, deliver, refs):
    return dict(title=title,question=question,steps=steps,deliver=deliver,resources=refs.split())
def E(claim,status,assessment,refs):
    return dict(claim=claim,status=status,assessment=assessment,resources=refs.split())
specialisms=[]
def S(id,title,summary,scope,prereqs,tools,modules,projects,claims,reading,frontier,categories,related):
    for i,m in enumerate(modules):
        m['id']=f'{id}-{i+1}'
        m['level']=['Foundation','Foundation','Intermediate','Intermediate','Advanced','Research bridge'][i]
    specialisms.append(dict(id=id,title=title,summary=summary,scope=scope,prereqs=[f'P{p:03}' for p in prereqs],tools=tools.split(),modules=modules,projects=projects,claims=claims,reading=[dict(resource=r,use=u) for r,u in reading],frontier=dict(text=frontier,categories=categories.split()),related=related.split()))

S('sound','Sound & acoustics','Follow a vibration from its source to a wave, a spectrum, a resonant pattern, and a measurement.',
'Start with physical waves and algebra. Move to Fourier analysis and boundary-value models after calculus. Music, room acoustics, and astronomical sonification are linked applications.',[3,4,27,28,47,11,14], 'acoustic_beats oscillator rlc',[
M('Waves you can describe','Sound is a mechanical disturbance: the medium oscillates while energy and information propagate.',[
L('A moving disturbance','Displacement and pressure | Longitudinal and transverse motion | Amplitude, period, frequency, and phase','Sketch the particle motion at five positions at one instant; then sketch one particle over time.'),
L('Speed, wavelength, and scale','λ = c/f and dimensional checks | Material and temperature dependence | Wavelength relative to an object','Use 343 m/s as an assumed air sound speed; compare wavelengths at 100 Hz and 1 kHz.'),
L('Energy and level','Intensity versus pressure amplitude | Logarithmic decibel ratios | Geometric spreading and its limits','Show that doubling intensity adds about 3 dB, while doubling pressure amplitude adds about 6 dB in the same medium.')],
'Explain why a pressure wave needs a medium and why sound level cannot be inferred from an uncalibrated recording alone.','up1 mitwaves russell'),
M('Pitch, harmony, and beating','Pitch perception and a physical frequency are related but distinct; harmonics describe a signal’s components.',[
L('Simple and complex tones','Sinusoidal reference tones | Fundamental and harmonic frequencies | Timbre and spectral envelope','Compare a sine, triangle, and sawtooth wave at the same fundamental using synthesized data.'),
L('Interference and beats','Superposition with phase | Sum-to-product identity | Beat frequency and envelope','Derive the equal-amplitude 440 Hz plus 442 Hz envelope and check the calculator.'),
L('Tuning systems','Octave as frequency ratio 2 | Equal temperament fₙ = f₀2^(n/12) | Rational intervals and accumulated mismatch','Compare a just 3:2 fifth with seven equal-tempered semitones; report the difference in cents.')],
'Distinguish beat rate, carrier oscillation, fundamental frequency, and perceived timbre using one plotted example.','mitwaves signals'),
M('Standing waves and visible modes','The equation, geometry, support, and drive jointly determine a resonant pattern.',[
L('Strings and air columns','Fixed and free boundaries | Nodes and antinodes | Open and one-end-closed tube fundamentals','Predict the first three ideal resonances of a 1 m tube for both boundary choices.'),
L('Damping and forced response','Natural versus driven frequency | Resonance width and quality factor | Energy input and dissipation','Sweep a simulated damped oscillator and explain why its peak stays finite.'),
L('Chladni patterns and cymatics','Nodal lines on a driven plate | Support and excitation position | Plate bending versus membrane tension','Annotate the Harvard demonstration: mark the support, drive, and observed nodes; state why a membrane model is only an analogy.')],
'Predict how changing a boundary can change a mode without invoking a special universal frequency.','chladni mitwaves russell'),
M('From waveform to measurement','A spectrum is an estimate with choices: sampling rate, record length, window, normalization, and calibration.',[
L('Sampling and aliasing','Sample interval and Nyquist limit | Aliased frequency | Anti-alias filtering before acquisition','Sample a synthetic tone above half the sample rate and predict its apparent frequency.'),
L('Fourier analysis','Discrete frequency bins | Window leakage and resolution | Amplitude spectrum versus power spectral density','Change the record length and window for two close tones; report resolution and units.'),
L('Time-frequency structure','Short-time transforms | Window-duration tradeoff | Onsets, chirps, and spectrogram color scales','Make a chirp spectrogram with two window sizes; explain the differences without claiming one is universally better.')],
'Reproduce a frequency estimate from a saved signal and metadata; account for leakage and measurement uncertainty.','fft signals audacity'),
M('Rooms, microphones, and noise','An observed recording combines source behavior, propagation, instrument response, and background noise.',[
L('Room response','Direct sound and reflections | Impulse response and convolution | Reverberation versus discrete echo','Convolve a test pulse with a synthetic room response and identify each delayed reflection.'),
L('Measurement chains','Transducer frequency response | Gain, clipping, and quantization | Calibration reference and noise floor','Create a recording log with device, distance, gain, sample rate, and clipping check.'),
L('A fair comparison','Repeated trials | Background subtraction assumptions | Uncertainty and environmental changes','Compare two room positions using the same source settings; plot variability across repeats.')],
'Identify which conclusions your recording supports and which require calibrated instrumentation.','signals audacity up1'),
M('Advanced acoustics and research','Connect the wave equation to scattering, nonlinear propagation, engineered materials, and scientific representations.',[
L('Beyond the simplest wave','Acoustic impedance and reflection | Scattering relative to wavelength | Nonlinearity and shock formation','Explain which small-amplitude assumptions would fail for a strongly driven wave.'),
L('Ultrasound and engineered media','Imaging time-of-flight | Attenuation and resolution tradeoffs | Metamaterial unit cells and effective models','Build a paper worksheet separating measured transmission from an effective-parameter interpretation.'),
L('Sound in astronomy','Pressure waves in cluster gas | Frequency shifting for audibility | Sonification as a mapping of other data','Compare the Perseus explanation with a NASA data sonification; label the measured variable and every audio mapping.')],
'Read one acoustics paper and identify its governing model, boundary conditions, measured observable, and validation baseline.','mitwaves perseussound sonification')],
[
J('Replicate a two-tone spectrum','When can a finite recording resolve two nearby frequencies?', ['Generate 440 and 442 Hz tones in Python at a stated sample rate.','Vary recording length and FFT window; retain original arrays.','Compare spectral peaks with the analytic beat envelope and examine leakage.','Write down frequency resolution, normalization, and the equal-amplitude assumption.'],'Notebook, waveform and spectrum figures, and a table of estimator errors.','fft signals'),
J('Map a family of resonant modes','Which features come from geometry and which come from excitation?', ['Study the Harvard plate demonstration and MIT mode lessons.','Begin with an analytic rectangular membrane model; label it as a different physical system from a bending plate.','Plot several mode shapes and their zero contours.','Vary aspect ratio and explain the resulting frequencies and degeneracies.'],'Mode atlas with equations, boundary conditions, and a plate-versus-membrane comparison.','chladni mitwaves sympy')],
[
E('Visible vibration patterns establish special healing frequencies.','Unsupported inference','Chladni patterns demonstrate standing-wave modes of a driven physical system. They do not by themselves establish a medical or spiritual mechanism.','chladni'),
E('NASA recordings mean ordinary sound travels through empty space.','Different physical cases','Pressure waves can exist in cluster gas. Other sonifications map non-acoustic measurements to sound; the mapping must be described.','perseussound sonification')],
[('mitwaves','Start with oscillations and mechanical waves; use lecture 11 for sound.'),('signals','Use the spectral-analysis sections only after recording units and sampling assumptions.'),('russell','Predict each animation before playing it; write down the boundary conditions.')],
'Follow classical-wave models, nonlinear dynamics, and audio signal processing. Pick a specific observable and reproduce a baseline before treating an unusual pattern as a new effect.','physics.class-ph eess.AS nlin.CD','geometry sacred-geometry astronomy')

S('geometry','Geometry','Build exact arguments, constructions, symmetries, and curved-space intuition before applying geometry to physics.',
'The sequence moves from school geometry to proof, computation, and differential geometry. Diagrams suggest relationships; derivations establish them under stated assumptions.',[3,4,7,9,17,18], 'regular_polygon golden_ratio',[
M('Points, assumptions, and proof','Geometry begins by specifying the objects and rules of the space being studied.',[
L('Language of a diagram','Points, lines, segments, and rays | Angle and distance | Definition versus observed appearance','Draw a figure with an unmarked apparent right angle; explain why the drawing alone proves nothing.'),
L('Congruence and similarity','Rigid motions | Triangle criteria | Ratios and scale factors','Prove two triangles similar and use the ratio to infer an inaccessible length.'),
L('A deductive argument','Hypotheses and conclusions | Euclid’s definitions and postulates | Counterexample and converse','Compare a statement, its converse, and a counterexample using quadrilaterals.')],
'Write a proof in which each step cites a definition, earlier result, or explicit assumption.','euclid math'),
M('Compass, straightedge, and coordinates','The same construction can be described synthetically and checked algebraically.',[
L('Intersecting circles','Equal-radius circles | Equilateral triangle construction | Perpendicular bisector','Recreate Euclid I.1 and prove equality of all three sides from the circle definitions.'),
L('Coordinate geometry','Slope and vector displacement | Dot product and orthogonality | Circle and line equations','Solve the equal-circle intersections symbolically and compare them with the construction.'),
L('Conics and loci','Focus and directrix | Ellipse, parabola, hyperbola | Geometric versus implicit descriptions','Derive a parabola equation from the equal-distance definition.')],
'Check one construction both by proof and exact SymPy intersections; list any nondegeneracy assumptions.','euclid symgeometry linear'),
M('Symmetry, polygons, and tiling','A symmetry is a transformation preserving a specified structure.',[
L('Regular polygons','Central and interior angles | Circumradius and side length | Triangulation for area','Derive the regular-polygon calculator formulas and test n = 3, 4, and 6.'),
L('Transformations','Translations and rotations | Reflections and compositions | Symmetry groups through examples','Compose two reflections and determine when the result is a rotation or translation.'),
L('Repeating patterns','Fundamental region | Edge matching and local angle sums | Geometric ornament in context','Reconstruct one Met teaching pattern and mark its translations and rotation centers.')],
'Explain why a visual motif and its full repeating pattern can have different symmetry descriptions.','metpatterns euclid symgeometry'),
M('Proportion and growth','An exact ratio is a mathematical property; applying it to a measured object needs a measurement rule.',[
L('The golden ratio','Self-similar rectangle | φ² = φ + 1 | Positive and negative algebraic roots','Derive φ from removing a square; use the rectangle calculator to verify the remaining aspect ratio.'),
L('Fibonacci and convergence','Second-order recurrence | Consecutive-term ratios | Dominant characteristic root','Compute ratio errors for the first 20 terms and explain why the convergence is not exact at finite n.'),
L('Spirals and evidence','Logarithmic spiral definition | Golden spiral as a special growth factor | Quarter-circle approximation','Plot a logarithmic spiral and a chain of quarter-circle arcs; quantify their mismatch.')],
'State exactly where φ is proved and where a numerical or visual approximation is being used.','goldenmyths sympy'),
M('Solid geometry and spatial reasoning','Move from planar pieces to surfaces, volumes, and combinatorial structure.',[
L('Nets and polyhedra','Faces, edges, vertices | Surface area and volume | Convexity and Euler’s formula','Construct a cube net and verify V − E + F = 2; explain the scope of the formula used.'),
L('Regular solids','Regular faces and equal vertex arrangement | Angle restriction at a convex vertex | The five convex Platonic solids','Use the angle condition to restrict possible face and vertex combinations.'),
L('Historical models','Kepler’s nested solids | Predicted versus observed distances | Model revision after new evidence','Reconstruct the logic of the 1596 model without presenting it as current Solar-System physics.')],
'Distinguish a valid geometric construction from an empirically successful model of nature.','euclid keplersolids pacioli'),
M('Curvature and geometry in physics','Local distances and global shape introduce new questions beyond a flat plane.',[
L('Spherical geometry','Great circles and geodesics | Triangle angle excess | Local flat approximation','Construct a spherical triangle with three right angles and state why Euclidean angle sums do not apply.'),
L('Curves and surfaces','Parametrization and tangent | Arc length and curvature | Intrinsic versus extrinsic properties','Compute the curvature of a circle and compare a cylinder’s local metric with that of a plane.'),
L('From geometry to fields','Metric and coordinate choice | Symmetry and conservation | Spacetime requires a different metric signature','Explain which parts of a sphere analogy help with GR and which fail for spacetime.')],
'Compute a simple length from a metric and distinguish a coordinate artifact from geometric curvature.','geometries mitgeometry tonggr')],
[
J('An exact construction notebook','Can numerical drawings and symbolic geometry verify the same construction?', ['Implement equal circles, an equilateral triangle, a perpendicular bisector, and a regular hexagon with SymPy.','Keep exact radicals until display time.','Test a degenerate input and explain the failure.','Compare symbolic lengths and areas with the built-in polygon calculator.'],'Four constructions, proofs, exact outputs, and a brief numerical-error note.','symgeometry euclid'),
J('Flat versus spherical triangles','How does curvature change triangle geometry?', ['Choose points on a unit sphere and connect them by shorter great-circle arcs.','Calculate side angles and spherical interior angles.','Compare a small triangle with a hemisphere-scale example.','Report angle excess and the assumptions used to choose each geodesic.'],'Reproducible notebook and an annotated comparison figure.','geometries mitgeometry')],
[E('A different geometry makes Euclid wrong.','Assumptions differ','Euclidean results are conditional on Euclidean assumptions. Spherical and hyperbolic models change those assumptions.','geometries'),E('A spiral-looking object must follow φ.','Measurement needed','Many curves are logarithmic or only approximately spiral. A golden spiral is one specific case; define and fit a model before naming it.','goldenmyths')],
[('euclid','Book I for constructions and proof; similarity before Book XIII on regular solids.'),('symgeometry','Use exact geometry to check intersections and distances.'),('mitgeometry','Begin after multivariable calculus, linear algebra, and proof practice.')],
'Study metric geometry, differential geometry, and computational methods. Separate a theorem’s hypotheses from its use as a physical model.','math.MG math.DG physics.class-ph','sacred-geometry sound astrophysics')

S('sacred-geometry','Sacred geometry','Explore exact constructions alongside the meanings given to them in specific artistic, religious, and historical settings.',
'This is a comparative learning framework, not a claim that all traditions form one ancient doctrine. Mathematical, historical, symbolic, and physical statements need different kinds of evidence.',[3,18,104], 'regular_polygon golden_ratio',[
M('Form, meaning, and kinds of evidence','A construction can be proved, an object dated, a belief described, and a physical effect tested: these are different tasks.',[
L('Define the question','Mathematical property | Historical attribution | Religious or symbolic interpretation','Classify four statements about one pattern and specify what evidence each would require.'),
L('Read an object record','Material, place, and date | Provenance and uncertain attribution | Museum interpretation versus original inscription','Create an object card using a named museum record; retain any approximate date.'),
L('Avoid a universal backstory','Shared forms across cultures | Independent construction possibilities | Documented transmission versus resemblance','List two ways similar patterns could arise without contact; state what would support transmission.')],
'Describe a geometric object’s exact properties and cultural context without treating either as proof of the other.','metpatterns mandala yantra'),
M('Circles, lenses, and contemporary motifs','Simple circle grids generate many forms; the history of a shape and the history of a name are separate questions.',[
L('Equal-circle construction','Centers one radius apart | Intersection lens and equilateral triangles | Exact height and width','Derive the intersection coordinates and the √3 ratio under this precise construction.'),
L('Rosettes and circle grids','Sixfold arrangement | Repeated compass radius | Visible edges versus chosen emphasis','Build a sixfold circle grid and show how highlighting different arcs changes the motif.'),
L('Names and lineage','Vesica construction and historical mandorlas | Flower of Life in contemporary discussion | Metatron’s Cube and attribution checks','Create separate columns for a drawn construction, a dated object, and the earliest verified use of a name; leave unknown dates blank.')],
'Explain why an old intersecting-circle construction does not establish every modern name or claimed uninterrupted lineage.','euclid mandorla metpatterns'),
M('Islamic geometric arts','Study the selected objects as works made in particular places, periods, materials, and contexts.',[
L('Grids and construction','Square and triangular grids | Compass divisions | Local construction marks','Follow one Met activity and keep the construction layer visible beneath the final pattern.'),
L('Repeat and interlace','Translation cell | Rotation and reflection | Interlaced bands and figure-ground choices','Find a minimal repeating region and distinguish visual interlace from a new mathematical symmetry.'),
L('Objects and interpretation','Tile, manuscript, and architecture | Region and period | Limits of generalized spiritual readings','Compare two named objects and state which meanings their records support and which remain your interpretation.')],
'Deliver an accurate reconstruction with a source object, date, construction method, and symmetry description.','metpatterns'),
M('Mandalas and yantras','Ritual diagrams and objects belong to living traditions with specific functions and interpretations.',[
L('Buddhist mandalas','Palace and cosmos representations | Visualization and ritual settings | Painted, sculptural, and architectural forms','Compare two Rubin examples while retaining each object’s place and date.'),
L('A situated yantra','Northern Indian eighteenth-century plaque | Mantras and ritual association | Object form beyond a generic diagram','Make a careful record of British Museum 1940,0716.329; mark the full-page access limitation.'),
L('Comparison without flattening','Center, enclosure, and orientation | Named tradition and practice | Similar geometry with different meanings','Compare formal organization while quoting no unsupported universal spiritual rule.')],
'Explain a selected object’s documented role as a tradition-specific account, without translating sacred terms into measured physical quantities.','mandala yantra'),
M('European proportion, iconography, and cosmology','Historical authors used geometry for illustration, theology, architecture, and explanatory models in different ways.',[
L('Pacioli and illustrated proportion','Divina proportione, 1509 | Polyhedral illustrations after Leonardo | Book evidence versus painting overlays','Read the Met book record and list what it establishes about date, authorship, and illustration.'),
L('Mandorla and sacred imagery','A c. 1406 tabernacle frame | Iconographic enclosure | Exact circle-lens ratio not guaranteed','Compare the recorded mandorla with your exact circle construction; avoid inferring a design method from silhouette alone.'),
L('Kepler’s nested solids','Mysterium Cosmographicum, 1596 | Six then-known planets | Theological motivation and empirical testing','Map the model’s intended explanation, its geometric apparatus, and the data needed to assess it.')],
'Distinguish historical meaning, mathematical elegance, and predictive success for one documented example.','pacioli mandorla keplersolids'),
M('Nature, cymatics, and claim evaluation','A pattern is the start of an investigation, not a complete causal explanation.',[
L('Golden-ratio claims','Exact mathematical examples | Approximate growth patterns | Flexible overlays and selection bias','Predefine endpoints and tolerance before measuring an image; compare against at least two alternative ratios.'),
L('Sound makes shapes','Standing waves and nodal lines | Boundary and drive dependence | Visual resemblance versus physical mechanism','Use the Chladni source to explain a pattern, then identify what a claimed biological effect would need beyond that demonstration.'),
L('A reproducible claim audit','Operational definition | Independent evidence and controls | Unverified versus refuted versus untestable','Write a one-page audit that preserves a tradition’s stated meaning while assessing a separate physical claim.')],
'Produce a claim ledger that labels evidence accurately and leaves unsupported ancestry or mechanisms unresolved.','goldenmyths chladni')],
[
J('A contextual pattern atlas','How can the same mathematical tools serve distinct artistic purposes?', ['Select one Met geometric-design activity, one Rubin mandala, and the Pacioli book record.','Draw an original schematic for each and identify exact versus approximate geometry.','Attach place, date, material, function, and source-access notes.','Compare similarities without asserting a common origin.'],'Three attributed study sheets and a comparison of form, use, and evidence.','metpatterns mandala pacioli'),
J('Test a golden-ratio overlay','Would the apparent fit survive a measurement rule chosen in advance?', ['Choose an image with a clear scale or dimensions and record why it was selected.','Predefine endpoints, tolerance, and comparison ratios.','Repeat measurements or vary plausible boundary placement.','Report every tested ratio and avoid claiming the maker’s intention from numerical agreement alone.'],'Measurement table, uncertainty plot, and an attribution-limit statement.','goldenmyths')],
[E('All sacred geometry is one ancient scientific system.','Not established by these sources','The sources document distinct objects and traditions. Their comparison here is an editorial framework, not evidence of a single lineage.','metpatterns mandala pacioli'),E('Flower of Life and Metatron’s Cube have a verified uninterrupted ancient lineage.','Attribution unresolved','This research did not verify ancient use of those exact names or an uninterrupted transmission. The constructions can be studied without asserting that history.','euclid metpatterns'),E('The golden ratio guarantees a healing or energy effect.','Unsupported physical inference','An exact proportion alone specifies no mechanism or measured outcome. A physical claim needs an operational test beyond visual similarity.','goldenmyths chladni')],
[('metpatterns','Begin with one construction activity and its named source object.'),('mandala','Read the institutional context before comparing geometric forms.'),('pacioli','Use the dated book as primary material evidence.'),('goldenmyths','Audit measurements and avoid selecting only convenient overlays.')],
'For further study, use museum catalogues and critical editions for history; geometry and wave papers for mathematical or physical questions. A mathematics-history feed is discovery, not an endorsement of esoteric claims.','math.HO math.MG','geometry sound newton-esoteric tesla-esoteric')

S('astrophysics','Astrophysics','Use mechanics, radiation, thermodynamics, nuclear physics, and inference to explain astronomical systems.',
'Astronomy asks how to observe and measure; this room emphasizes the physical mechanisms inferred from those observations. Start with scaling models, then test their assumptions against data.',[4,14,26,52,60,75,79,90,92,93], 'stellar_scaling orbit photon schwarzschild',[
M('Scales, radiation, and physical inference','Distance turns a measured flux into a luminosity; the uncertainty follows the inference.',[
L('Astronomical scales','AU, parsec, and light-year | Orders of magnitude | Dynamical, thermal, and light-crossing times','Estimate and compare orbital and light-crossing times for an Earth-like orbit.'),
L('Radiation as a diagnostic','Flux and luminosity | Inverse-square model | Blackbody spectrum and color','Derive the luminosity-temperature-radius scaling and explore the stellar calculator.'),
L('Spectra and uncertainty','Atomic transitions | Doppler shift in its regime | Extinction and parameter degeneracy','Explain two distinct reasons a star could look red and how additional data could distinguish them.')],
'Translate a measured flux into a luminosity with explicit distance, geometry, and extinction assumptions.','astronomybook mitastro nasaems'),
M('Stellar structure','A star’s structure balances forces and transports energy under an evolving composition.',[
L('Mechanical balance','Hydrostatic equilibrium | Pressure gradient and enclosed mass | Order-of-magnitude central conditions','Derive a pressure scale from gravity and state which density assumption you used.'),
L('Energy generation and transport','Nuclear reactions and mass defect | Radiative diffusion | Convective instability as a model criterion','Trace energy from a stellar core to the photosphere and distinguish particle travel from energy transport.'),
L('Scaling models','Stefan–Boltzmann law | Effective temperature versus interior temperature | Homology assumptions and their limits','Compare equal-temperature stars of radii R and 2R; explain why luminosity changes by four.')],
'Draw the coupled structure problem and name the equation of state, opacity, and energy-generation inputs it requires.','astronomybook mitastro up2'),
M('Formation and evolution','Mass, composition, and environment shape a star’s path through observable states.',[
L('Gas to protostar','Self-gravity and pressure support | Cooling and collapse | Angular momentum and disks','Estimate a gravitational collapse timescale and identify what the simplified model omits.'),
L('The Hertzsprung–Russell diagram','Luminosity and effective temperature | Main sequence and evolved branches | Population versus time-track interpretation','Explain why a scatter plot of many stars is not automatically the life history of one star.'),
L('Endpoints and enrichment','White dwarfs and degeneracy | Massive-star collapse | Nucleosynthesis and chemical enrichment','Compare two mass-dependent evolution pathways and mark where the simple picture needs binaries or rotation.')],
'Use a diagram to connect a stellar population to physical models without mistaking selection effects for evolution.','astronomybook mitastro'),
M('Compact objects and transients','Extreme gravity connects observables to strong-field dynamics and radiation mechanisms.',[
L('Compactness','Escape-speed heuristic | Schwarzschild radius | Event horizon versus material surface','Calculate characteristic radii for two masses and state the nonrotating assumption.'),
L('Accretion and radiation','Gravitational energy release | Angular momentum transport | Spectrum and timing diagnostics','Compare accretion energy per unit mass with a nuclear-energy scale; label the approximations.'),
L('Multi-messenger events','Electromagnetic light curves | Gravitational-wave strain | Joint localization and model uncertainty','Read one GWOSC tutorial and distinguish detector data from the inferred source parameters.')],
'Explain how a compact-object parameter is inferred and name an alternative or systematic that could change it.','gwosc astronomybook tonggr'),
M('Galaxies and cosmology','Observations at large scales require dynamical models and a careful account of cosmic expansion.',[
L('Galactic dynamics','Rotation curves | Mass-to-light inference | Baryonic and dark-matter model components','Compute enclosed mass in a spherical approximation and identify why a disk complicates it.'),
L('Expansion and distances','Redshift and scale factor | Luminosity versus angular-diameter distance | Cosmological parameters and assumptions','Use Astropy to compare distance definitions at a stated redshift and cosmology.'),
L('Structure and evidence','Density perturbations | Selection functions and survey windows | Model comparison across independent probes','Map which measurements constrain geometry, growth, and matter content separately.')],
'Avoid applying a low-redshift approximation outside its regime; name the cosmology behind every derived distance.','tongcosmo astropy astronomybook'),
M('Reproducible astrophysical research','A credible result ties a physical model to a measurement process and an inspectable analysis.',[
L('Numerical models','Discretization and convergence | Conservation diagnostics | Parameter and resolution sweeps','Integrate an orbit with REBOUND and separate numerical energy drift from physical model limitations.'),
L('Statistical inference','Likelihood and noise model | Priors and degeneracy | Posterior predictive checks','Fit a synthetic radiation dataset and inspect whether the fitted model reproduces its residual structure.'),
L('Frontier reading','Paper version and publication status | Central figure replication | Baseline, uncertainty, and untested regime','Choose one recent astrophysics preprint and design the smallest useful replication before adding complexity.')],
'Deliver a pinned dataset, explicit model, uncertainty analysis, and a result that another learner can reproduce.','rebound astropy gwosc')],
[
J('A Gaia stellar-population diagram','Which features survive your quality and distance choices?', ['Select a named Gaia data release and a small reproducible query.','Document photometry and astrometry quality filters and sample selection.','Begin with high signal-to-noise positive parallaxes; quantify the selection limitation.','Build a color–absolute-magnitude diagram and compare it with an uncertainty-aware distance approach.'],'Query, environment record, selection table, diagram, and distance-inference caveats.','gaia astropy astronomybook'),
J('Replicate an orbital stability experiment','How do numerical settings affect your physical conclusion?', ['Start from a documented REBOUND example and record masses, units, and initial conditions.','Run a two-body baseline and monitor conserved quantities.','Add one perturber and vary time step or tolerance.','Separate convergence from genuine changes across initial conditions.'],'Notebook, conservation plots, parameter table, and a carefully scoped stability claim.','rebound')],
[E('A stellar temperature alone determines luminosity.','Incomplete model','Stefan–Boltzmann scaling also needs emitting area; real spectra and inferred effective temperatures bring additional model assumptions.','astronomybook'),E('A compelling simulation uniquely proves its physical interpretation.','Inference requires comparison','Convergence checks address numerical error. Physical adequacy also needs data, competing models, and realistic measurement assumptions.','mitastro astropy')],
[('astronomybook','Use radiation and stellar chapters before galaxies and cosmology.'),('mitastro','Work quantitative problems alongside the introductory text.'),('gwosc','Start with a published tutorial dataset before an original event analysis.')],
'Track stellar physics, galaxies, high-energy astrophysics, and cosmology. These feeds retrieve recent submissions, not a complete or automatically peer-reviewed literature review.','astro-ph.SR astro-ph.GA astro-ph.HE astro-ph.CO gr-qc','astronomy sound geometry')

S('astronomy','Astronomy & observing','Learn the sky, instruments, coordinates, and data methods that make astrophysical questions measurable.',
'Begin with a planetarium and public datasets. A telescope is optional. Record location, time system, instrument, data release, and calibration before interpreting a result.',[3,4,14,15,26,48,49,96,107], 'astrometry orbit lens diffraction photon',[
M('Find your way around the sky','An object’s apparent position depends on reference frame, observer location, and time.',[
L('The visible sky','Horizon and zenith | Altitude and azimuth | Diurnal motion','Set your location and two times in Stellarium; predict how one star’s altitude changes.'),
L('Celestial coordinates','Right ascension and declination | Equatorial versus ecliptic frames | Epoch, frame, and proper motion','Transform a catalog coordinate into an observing direction using a documented Astropy tutorial.'),
L('Time and seasons','Solar versus sidereal day | Earth’s axial tilt | Time zones and observation timestamps','Explain seasons using illumination geometry and distinguish local civil time from an archival timestamp.')],
'Write an unambiguous observing record with position frame, observer location, timestamp, and time system.','astronomybook stellarium astropy'),
M('The Solar System as a laboratory','Repeated observations reveal geometry, motion, and illumination without requiring a large instrument.',[
L('Moon and planetary appearance','Phases from viewing geometry | Opposition and conjunction | Angular size versus physical size','Sketch Sun–Earth–Moon geometry for four lunar phases and explain the observed illuminated fraction.'),
L('Orbits and ephemerides','Keplerian elements | Perturbations and prediction | Model ephemeris versus measurement','Compare a simple two-body prediction with a planetarium position and list omitted effects.'),
L('Planetary science','Surfaces and atmospheres | Reflected versus thermal radiation | Selection by wavelength','Choose two wavelength bands for a planetary question and explain what each can reveal.')],
'Explain an apparent motion or phase change with a geometric model and a reproducible time sequence.','astronomybook stellarium rebound'),
M('Instruments and the electromagnetic sky','Collecting area, angular resolution, detector response, and observing conditions set different limits.',[
L('Telescope optics','Aperture and focal length | Image scale | Diffraction and seeing','Use the diffraction calculator to predict an ideal angular resolution, then explain atmospheric limitations.'),
L('Detectors and calibration','Bias, dark, and flat-field concepts | Gain and read noise | Saturation and linear response','Trace a raw pixel value through a calibration equation and record the units at each step.'),
L('Multiwavelength observing','Radio to gamma rays | Atmospheric transmission | Different instruments and selection effects','Use NASA’s spectrum guide to match a physical question to a detector band.')],
'Explain why magnification alone does not determine resolving power or sensitivity. For direct solar work, use a qualified observatory’s dedicated solar procedure and equipment.','astronomybook nasaems up3'),
M('Photometry, spectroscopy, and light curves','Measurements become useful when their extraction method and calibration are explicit.',[
L('Measuring brightness','Aperture and background annulus | Instrumental and calibrated magnitude | Comparison stars','Use a synthetic star image to test how background choice changes measured flux.'),
L('Reading a spectrum','Wavelength calibration | Continuum and line features | Resolution and Doppler estimates','Fit one synthetic line, vary noise and resolution, and report the uncertainty in its center.'),
L('Time-series analysis','Cadence and gaps | Detrending and signal distortion | Period searches and false alarms','Reproduce a Lightkurve tutorial and compare raw and detrended data before inspecting a periodogram.')],
'Produce a brightness or spectral measurement with units, calibration assumptions, and an uncertainty estimate.','lightkurve signals astronomybook'),
M('Astrometry and distances','Distance is inferred from a measurement model, not read directly from a telescope image.',[
L('Parallax geometry','Annual baseline | Arcseconds and milliarcseconds | d(pc) = 1000/p(mas)','Derive the small-angle parallax relation and test the astrometry calculator at 10 mas.'),
L('Uncertainty and selection','Local error propagation | Noisy and negative measured parallaxes | Distance inference and priors','Explain why discarding every negative parallax can bias a sample; restrict the simple calculator to its stated regime.'),
L('Positions over time','Proper motion versus radial velocity | Tangential speed and distance | Reference frames and systematics','Create a data dictionary separating position, proper motion, parallax, and their uncertainties.')],
'Use inverse parallax only with an explicit accuracy assessment; explain why a negative measurement is not a negative physical distance.','gaia astropy astronomybook'),
M('Survey science and responsible discovery','A candidate signal becomes a scientific claim through validation, reproducibility, and independent evidence.',[
L('Working with archives','FITS and table metadata | Release identifiers and quality flags | Reproducible queries','Download a small public example and preserve its identifier, query, units, and access date.'),
L('Transit and transient candidates','Period and phase folding | Instrumental artifacts | False positives and follow-up','Run the known-planet tutorial, inspect an alternative explanation, and label the exercise as replication.'),
L('A reading and observing program','Question-driven observing plan | Log and uncertainty budget | Recent-paper worksheet','Choose one achievable monthly question and define the measurement that would count as progress.')],
'Publish a reproducible study notebook that distinguishes measured signal, candidate interpretation, and confirmed result.','transitlab lightkurve gaia')],
[
J('Replicate a known exoplanet transit','Can you recover a documented period and identify what could mimic it?', ['Follow the official Lightkurve box least squares tutorial.','Record mission, target, data product, quality masks, and detrending choices.','Recover the period and inspect phase-folded and unbinned data.','Check how injected or removed trends change the result; discuss common false positives.'],'Notebook, light curve, period search, and a replication statement.','transitlab lightkurve'),
J('A reproducible sky notebook','Can another observer reconstruct what you planned to observe?', ['Choose a location and week in Stellarium; record time zone and coordinates.','Select three targets with different sky motions.','Predict altitude at two times and save the calculation inputs.','Compare a safe naked-eye observation or a documented simulation with the prediction.'],'Observing log, coordinate table, original sketches, and a model-versus-observation note.','stellarium astropy astronomybook')],
[E('A periodic dip alone confirms a new exoplanet.','Candidate evidence','A period-search output needs checks for instrumental and astrophysical alternatives. Recovering a known tutorial target is a learning replication.','transitlab'),E('Inverse parallax is an unbiased distance estimate for every star.','Limited approximation','The nonlinear transformation and sample selection matter. Low signal-to-noise parallaxes require a fuller inference rather than symmetric local error bars alone.','gaia astronomybook')],
[('astronomybook','Chapters 2–6 for sky, motion, radiation, and instruments.'),('stellarium','Predict positions before changing the simulated time.'),('astropy','Work through coordinate and table tutorials with explicit units.'),('lightkurve','Start with existing tutorials before designing a new search.')],
'Follow instruments, planetary astronomy, stellar variability, and survey methods. Archive releases and paper versions must be recorded explicitly.','astro-ph.IM astro-ph.EP astro-ph.SR','astrophysics sound geometry')

S('newton-esoteric','Newton · alchemy & sacred history','Read Newton’s chymistry, theology, prophecy, Temple studies, and ancient chronology through identifiable manuscripts and scholarly editions.',
'“Occult” is a broad modern label here. Newton’s alchemical, religious, and historical activities overlapped in a seventeenth-century setting but should not be reduced to one hidden doctrine. This page is textual and historical study.',[97,98,104], '',[
M('Place Newton’s chymistry in context','The surviving material combines reading, copying, interpretation, and experimental records.',[
L('Historical vocabulary','Chymistry and alchemy | Material transformations | Modern chemistry as a different framework','Build a glossary from the Indiana project and distinguish historical terms from modern chemical identities.'),
L('Kinds of documents','Laboratory notebooks | Indexes and recipes | Excerpts copied from other writers','Classify three archive items by document type before summarizing their content.'),
L('Author and copyist','Newton’s own statement | Quotation or paraphrase | Editorial attribution and uncertain readings','Annotate a short passage with speaker, document identifier, and editorial uncertainty.')],
'Explain why the archive’s roughly one million written and transcribed words cannot all be treated as Newton’s original assertions.','chymistry'),
M('Read laboratory and alchemical manuscripts','A historical experiment must be understood in its own materials, aims, and recording conventions.',[
L('A manuscript workflow','Catalogue metadata | Diplomatic versus normalized transcription | Folio and translation reference','Record the shelfmark and edition before interpreting a selected passage.'),
L('Observation and interpretation','Procedure versus reported outcome | Encoded or ambiguous material terms | Repeated trial and incomplete record','Create a table separating what was done, what was reported, and what the author inferred.'),
L('Textual replication','Compare transcriptions | Trace a cited predecessor | Explain unresolved terminology','Reconstruct a sequence on paper from a short excerpt; do not attempt historical chemical recipes.')],
'Produce a source-based account with uncertainties intact, avoiding modern substance identification where the evidence is ambiguous.','chymistry newton'),
M('Theology and restoration of knowledge','Newton treated scriptural interpretation and the history of doctrine as substantial intellectual work.',[
L('Religious questions','Scriptural authority | Historical change in doctrine | Seventeenth-century intellectual setting','Read Iliffe’s account and separate Newton’s position from the historian’s interpretation.'),
L('Anti-Trinitarian views','God and Jesus distinguished | Private study and contemporary orthodoxy | Evidence from surviving writings','Write a careful paragraph explaining the reported position without replacing it with a modern denominational label.'),
L('Ancient wisdom','Classical scholia | Lost or corrupted knowledge | Limits of a single unifying thesis','Compare two pursuits and ask what evidence actually connects them.')],
'Attribute historical interpretations and avoid claiming that all of Newton’s scientific work follows from one religious or alchemical system.','newtonreligion'),
M('Prophecy and the 2060 calculation','Read the arithmetic together with Newton’s own qualification and purpose.',[
L('Find the source','Yahuda MS 7.3g | Post-1700 catalogue dating | Folio 13v','Locate the calculation in the normalized transcription and record its manuscript identifier.'),
L('Reconstruct the reasoning','Prophetic period of 1,260 years | Chosen starting point AD 800 | Arithmetic reaching 2060','Reproduce the arithmetic while clearly marking the interpretive assumptions as theological rather than measured physical inputs.'),
L('Restore the qualification','Allowance for a later date | Concern about rash predictions | Lower bound versus fixed event forecast','Write two sentences that preserve the qualification and do not turn it into a destruction-of-Earth prediction.')],
'Explain both the calculation and why the common “Newton predicted the world ends in 2060” headline misrepresents this passage.','newton2060'),
M('Solomon’s Temple and the sacred cubit','Newton’s reconstructions combine textual study, ancient units, and reported measurements.',[
L('Text to plan','Biblical descriptions | Josephus and other sources | Conflicting architectural accounts','Draw a schematic with uncertain dimensions marked and sources attached.'),
L('Ancient metrology','Cubic and linear units | Comparison of reported lengths | Conversion uncertainty','Create a conversion table with ranges rather than unjustified exact modern values.'),
L('Pyramids in the argument','Comparative measurements | Sacred-cubit interpretation | Historical inference versus energy speculation','Identify the role of a pyramid measurement in the text without introducing a power-generation claim.')],
'Deliver a reconstruction that visibly distinguishes quoted measurements, inferred dimensions, and uncertain conversions.','newtontemple'),
M('Ancient chronology and later reception','A historical work can illuminate Newton’s aims even when its proposed reconstruction is not accepted today.',[
L('The 1728 publication','Posthumous Chronology | Ancient kingdoms and sequence | Chapter-level source trail','Choose one chapter and list the historical problem Newton is trying to solve.'),
L('Compare kinds of evidence','Textual testimony | Astronomical reasoning in chronology | Modern dating requires independent assessment','Select a claim and write what additional evidence would be needed to assess it today.'),
L('Audit a modern retelling','Quotation provenance | Selective excerpt and missing qualification | Unknown versus unsupported','Trace one popular Newton occult claim to a primary record, or mark the search unresolved.')],
'Create a claim ledger with source, date, Newton’s argument, modern assessment, and unresolved questions.','newtonchronology newtonreligion newton')],
[
J('A Newton manuscript dossier','What can one short document establish about Newton’s aims?', ['Select a short chymistry or theological passage with a stable identifier.','Record manuscript, date range, edition, and translation.','Separate copied material, reported observations, and interpretive claims.','Compare a modern summary with the complete local context.'],'Annotated source sheet, vocabulary glossary, and a 500-word evidence-based interpretation.','chymistry newtonreligion newton'),
J('Reconstruct the cubit argument','How sensitive is a historical reconstruction to its unit assumptions?', ['Read the Temple/cubit translation and choose a limited dimensional argument.','Record each historical measurement and its cited source.','Draw a plan using explicit assumed conversion ranges.','Show which conclusions change when a conversion changes.'],'Original plan, measurement table, sensitivity calculation, and source notes.','newtontemple')],
[E('Newton predicted the world would be destroyed in 2060.','Misleading summary','The manuscript gives 2060 as a possible lower bound in one prophetic interpretation, permits a later date, and criticizes rash predictions.','newton2060'),E('Every alchemical proposition in Newton’s papers was his own belief.','Authorship needs checking','The archive includes extensive transcriptions and excerpts alongside original writing and laboratory notes.','chymistry'),E('His Temple and pyramid studies establish a hidden energy technology.','Not supported by the cited work','The cited drafts concern architecture, texts, and ancient units. They do not establish such an energy mechanism.','newtontemple')],
[('chymistry','Begin with editorial context and one identified manuscript.'),('newtonreligion','Use the 2013 scholarly essay to frame theology and its interpretive limits.'),('newton2060','Read the qualification immediately surrounding folio 13v’s calculation.'),('newtontemple','Track the translation’s sources and uncertain dimensions.')],
'Follow new editorial work in the Newton Project and Indiana Chymistry archive. Archive completeness and digitization change; these gateways do not imply that every surviving work is included here.','','sacred-geometry geometry tesla-esoteric')

S('tesla-esoteric','Tesla · philosophy & unusual claims','Investigate Tesla’s visualization accounts, Vedanta encounter, ether models, planetary-signal speculation, and later mystical reputation.',
'These sources document a mixture of autobiography, philosophical analogy, historical physics, and speculation. They do not establish a hidden occult system. Tesla Universe provides readable reproductions; original periodical facsimiles were not independently checked in this review.',[40,41,42,102,103,104], 'rlc transformer acoustic_beats',[
M('Autobiography and mental invention','Tesla’s descriptions of his inner experiences are valuable testimony, with the limits of retrospective self-report.',[
L('Read My Early Life','Electrical Experimenter, February 1919 | Childhood recollections | Later narrative framing','Record the publication date separately from the much earlier events Tesla describes.'),
L('Visualization accounts','Vivid images and flashes | Imagined journeys | Mentally testing an invention','Separate the described experience from Tesla’s own proposed explanation of its cause.'),
L('Habits and interpretation','Counting steps and volumes | Repetition in multiples of three | No retrospective diagnosis','Explain why an autobiographical habit does not authenticate a universal mathematical theory.')],
'Summarize the memoir accurately as self-report without adding psychic powers, a diagnosis, or an unsupported 3–6–9 doctrine.','teslamemoir'),
M('Tesla and Vivekananda','A dated letter documents an encounter and anticipated work; its author and tense matter.',[
L('The correspondence','Vivekananda to E. T. Sturdy | New York, 13 February 1896 | Gathering connected with Sarah Bernhardt','Identify who is reporting the meeting and what access this gives us to Tesla’s views.'),
L('Terms in context','Prāṇa, ākāśa, and kalpas | Religious-philosophical vocabulary | Translation is not physical equivalence','Write a glossary tied to the letter; avoid replacing the terms with modern field quantities.'),
L('A proposed demonstration','Interest reported by Vivekananda | Anticipated further meeting | Prospective versus completed proof','Mark every claim about future work and state what a completed derivation would require as evidence.')],
'Explain what the letter supports and why it does not show Tesla deriving mass–energy equivalence or accepting all of Vedanta.','vivekananda'),
M('Ether and philosophical energy','Historical models and social analogies must be read according to the roles they play in the original text.',[
L('The 1891 lecture','High-frequency alternating currents | Mechanical ether language | A physical hypothesis of its period','Find Tesla’s ether discussion and place it before the 1896 Vivekananda meeting.'),
L('The 1900 essay','Engineering proposals | Human progress as mechanical analogy | Solidarity and religious references','Make two columns for measurable engineering quantities and the essay’s social metaphors.'),
L('Compare with modern physics','Model assumptions | Experimental tests and revision | Ether is not automatically a quantum vacuum','Choose one historical claim and specify a modern observable that could test an explicit version of it.')],
'Distinguish a historical physical medium, a philosophical metaphor, and a quantitatively defined modern model.','teslaether teslahuman'),
M('Talking with the Planets','An observed disturbance and a proposed intelligent origin are separate levels of claim.',[
L('Identify the publication','Collier’s Weekly, 9 February 1901 | Editorial introduction | Tesla’s first-person account','Mark the boundary between the introduction and Tesla’s own article.'),
L('Observation and speculation','Electrical disturbances in Colorado work | Later thought of intelligent control | No deciphered message','Create a timeline separating observation, interpretation, and proposed future work.'),
L('A signal-validation problem','Instrumental interference | Alternative physical explanations | Independent repeat observation','Design a general verification plan for an unusual signal without pretending this review determined its historical source.')],
'State that Tesla speculated about interplanetary communication without presenting it as confirmed extraterrestrial contact.','teslaplanets'),
M('Resonance, invention, and extraordinary claims','A real resonant circuit can be studied quantitatively without importing later legends into its operation.',[
L('The engineering foundation','Induction and coupled circuits | RLC resonance and losses | Voltage, current, and stored energy','Use the RLC calculator to distinguish resonant frequency from energy created or consumed.'),
L('Patents as documents','Claimed apparatus and method | Patent filing versus demonstrated performance | Independent measurements','Read a selected Tesla patent and identify one performance question it does not answer by itself.'),
L('Energy accounting','Input and output power | Stored versus continuously generated energy | Measurement bandwidth and load','Draw a power-accounting boundary for a simulated coupled circuit; identify every assumed loss.')],
'Explain an electrical mechanism using equations and measurable quantities; do not infer unlimited energy from a resonance peak.','teslapatents teslatransformer tesla1892 up2'),
M('3–6–9, quotations, and modern reception','A popular attribution needs a dated, traceable source before it can be used as Tesla’s testimony.',[
L('The provenance ladder','Original publication or letter | Reliable edition | Unsourced repetition','Build a quotation record with exact wording, claimed date, earliest located source, and access limits.'),
L('Two widely shared sayings','The 3–6–9 key-to-the-universe saying | The energy, frequency, vibration maxim | Habit evidence versus quotation evidence','Mark both attributions unverified in this review; do not turn failure to locate a source into proof of forgery.'),
L('Respectful critical reading','Documented interest | Speculative statement | Later interpretation and unresolved attribution','Rewrite a sensational Tesla story as a source-linked account that preserves what is interesting and what is unknown.')],
'Complete a claim audit with documented, autobiographical, speculative, and unverified statements clearly identified.','teslamemoir teslawritings tesla')],
[
J('A Tesla claims ledger','Which parts of a modern story survive a primary-source check?', ['Choose one claim each about visualization, Vivekananda, planetary signals, and 3–6–9.','Record the strongest located source with publication metadata.','Separate direct text, correspondent report, later paraphrase, and missing attribution.','Write an assessment with access limits and the evidence that could change it.'],'Four-entry evidence ledger with dated citations and an unresolved-questions column.','teslamemoir vivekananda teslaplanets'),
J('Resonance without mythology','Can a simple model account for the response while conserving energy?', ['Start with a low-voltage circuit simulation or numerical RLC model; no high-voltage build is required.','Sweep drive frequency at a fixed input definition.','Compute dissipation and changes in stored energy.','Compare the model with a historical apparatus description and list what the simplified model omits.'],'Simulation notebook, response curve, and an energy-accounting explanation.','up2 tesla1892 scipy')],
[E('Tesla proved Vedanta or derived E = mc² from it.','Not established by the letter','Vivekananda reports interest and an anticipated demonstration. The letter does not supply a completed derivation or establish wholesale acceptance.','vivekananda'),E('Vivekananda introduced Tesla to ether.','Chronology conflicts','Tesla’s 20 May 1891 lecture already uses ether language, before the documented 1896 encounter.','teslaether vivekananda'),E('Tesla confirmed communication from extraterrestrials.','Speculation, not confirmation','The 1901 article describes disturbances and a later intelligent-origin interpretation; no deciphered message or independent confirmation is established there.','teslaplanets'),E('The 3–6–9 and energy/frequency/vibration sayings are verified Tesla quotations.','Unverified attribution','No dated primary source for either saying was identified in this review. His reported multiples-of-three habits do not authenticate the quotations.','teslamemoir teslawritings')],
[('teslamemoir','Read the 1919 account as retrospective testimony.'),('vivekananda','Read the 13 February 1896 letter with attention to its author and future-tense claims.'),('teslaether','Compare the 1891 historical model with the later meeting chronology.'),('teslaplanets','Separate editorial framing, observed disturbances, and proposed interpretation.')],
'Use the Nikola Tesla Museum’s archive gateway and dated publications for historical research. A gateway or transcription collection is not the entire archive, and repeated online quotations are not independent evidence.','','sound sacred-geometry newton-esoteric')

for category,label in [('physics.class-ph','Classical physics and waves'),('eess.AS','Audio and speech processing'),('math.MG','Metric geometry'),('math.DG','Differential geometry'),('math.HO','History and overview of mathematics')]:
    feeds.append(dict(id=category,category=category,label=label,url='https://arxiv.org/list/'+category+'/recent',description='Manual discovery: up to eight recent submissions; metadata is not proof of peer review.'))
