"""Verify a clean detached candidate and emit its receipt outside the Git tree."""
import argparse,hashlib,json,runpy,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
BASE='205ca35c4e9e7f8e1d5cb484ebe01280fdd44fc5'
def require(ok,m):
    if not ok:raise ValueError(m)
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    p=argparse.ArgumentParser();p.add_argument('--expected-commit',required=True);p.add_argument('--expected-tree',required=True);p.add_argument('--output',required=True,type=Path);a=p.parse_args()
    out=a.output.resolve();require(not out.exists() and not out.is_relative_to(ROOT),'fresh external output');out.mkdir(parents=True)
    require(git('rev-parse','HEAD')==a.expected_commit and git('rev-parse','HEAD^{tree}')==a.expected_tree,'candidate identity')
    require(git('rev-parse','--abbrev-ref','HEAD')=='HEAD','must be detached')
    require(not git('status','--porcelain'),'must start clean')
    changed=git('diff','--name-only',BASE,'HEAD','--','research','evidence').splitlines()
    require(all(x.startswith('research/round25/') for x in changed),'historical research modified')
    historical=runpy.run_path(str(ROOT/'research/round24/admission.py'))
    for loop in historical['LOOPS']:historical['gate'](loop)
    checks=[]
    def run(name,cmd):
        r=subprocess.run(cmd,cwd=ROOT,capture_output=True,text=True);(out/(name+'.log')).write_text(r.stdout+r.stderr)
        require(r.returncode==0,'check failed '+name+'; see '+str(out/(name+'.log')))
        checks.append({'name':name,'command':cmd,'exit_code':r.returncode});print(name+': passed',flush=True)
    for optimized in [False,True]:
        mode='optimized' if optimized else 'normal';extra=['--optimized'] if optimized else []
        py=[sys.executable,'-B']+(['-O'] if optimized else [])
        run('aa-'+mode,py+['research/round25/admission.py','--output',str(out/('aa-'+mode)),*extra])
        run('inherited-y-'+mode,py+['research/round24/admission.py','--loops','y1','y2','--output',str(out/('y-'+mode)),*extra])
        run('gate-mutations-'+mode,py+['research/round25/test_admission.py'])
    # Remove generated destinations so a no-op builder cannot pass.
    expected={str(p.relative_to(ROOT)):digest(p) for p in [ROOT/'research/round25/all-results.json',ROOT/'research/round25/ALL_RESULTS.md',ROOT/'dist/research-round25-data.js',*sorted((ROOT/'docs').iterdir())] if p.is_file()}
    for name in ['research/round25/all-results.json','research/round25/ALL_RESULTS.md','dist/research-round25-data.js']:(ROOT/name).unlink()
    shutil.rmtree(ROOT/'docs')
    run('history-rebuild',[sys.executable,'-B','research/round25/build_history.py'])
    run('site-rebuild',[sys.executable,'-B','research/round25/build_site.py'])
    run('pages-rebuild',[sys.executable,'-B','scripts/build_pages.py'])
    require(all((ROOT/name).is_file() and digest(ROOT/name)==h for name,h in expected.items()),'generated bytes differ')
    for f in ['test_workbench','test_journey','test_round22','test_round23','test_round24','test_round25']:
        run(f,['node','tests/'+f+'.mjs'])
    require(not git('status','--porcelain'),'verification changed candidate')
    receipt={'status':'passed','commit':a.expected_commit,'tree':a.expected_tree,'baseline':BASE,
      'historical_round24_gates_validated':10,'new_producer_executions':4,'inherited_producer_executions':8,
      'checks':checks,'generated_files_compared':len(expected),'browser_visual_review':False,
      'authorship':'single agent; exact replays are correlated checks, not independent review'}
    (out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps({'status':'passed','receipt':str(out/'receipt.json'),'sha256':digest(out/'receipt.json')}))
if __name__=='__main__':main()
