from pathlib import Path
import ast,hashlib,json
ROOT=Path(__file__).resolve().parent;PROJECT=ROOT.parent
FILES=['round4/code/response.py','round3/code/backreaction.py','round5/proof_search.py','round5/symbolic_checks.py','round5/coefficient_certificate.py','round5/run_checks.py']
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
findings=[
 {'id':'C01','severity':'high for nonzero delayed probe experiments','title':'Comparison family centered at the wrong probe amplitude','file':'round4/code/response.py','lines':[298,359],'repro':'audit_repro.py: nonzero_probe; test_nonzero_probe_preparation_and_centered_difference','observed':'With probe_amp=0.5, old finite differences were centered at zero; gauge and translated runs also dropped the probe. Old field comparison differed by 0.5002586.','impact':'False rejection of a valid tangent and comparison of physically different source histories. Default probe_amp=0 is unaffected.','fix':'Center plus/minus runs at probe_amp ± epsilon, retain probe in gauge/translated runs, and mark legacy comparison unavailable when its source cannot match.','status':'fixed and reproduced'},
 {'id':'C02','severity':'medium','title':'Unvalidated scenario controls yield NaNs or silently select a model','file':'round4/code/response.py','lines':[150,165,298,332,363,379],'repro':'audit_repro.py: zero_epsilon and unknown_mode_accepted; bad-epsilon and mode regressions','observed':'Unknown mode misspelled is accepted; epsilon=0 emits NaN derivative arrays. Empty epsilons fail later at min(); duplicate epsilons collapse in CSV mapping.','impact':'Invalid diagnostic output or unintended comparison family; no evidence that accepted historical defaults contain this input defect.','fix':'Validate mode, nonfinite source controls, supported gauge flag, nonempty distinct positive finite epsilon values before integration. Also reject incomplete/nonfinite returned state arrays.','status':'fixed and reproduced'},
 {'id':'C03','severity':'high for automated acceptance','title':'Python optimization can disable mathematical acceptance checks','file':'round5/symbolic_checks.py; round5/coefficient_certificate.py; round5/run_checks.py','lines':[8,9,50,51,32,37,46,23,33],'repro':'test_historical_assert_mutant_false_success_reproduced and test_symbolic_gate_fails_even_optimized','observed':'A deliberately wrong Bloch identity (+1 defect), executed with python -O, returns exit code 0 and passed:false in historical symbolic code. The old aggregate runner checks only exit code.','impact':'A future optimized or inherited PYTHONOPTIMIZE run could be marked successful despite failed checks. The recorded nonoptimized historical run remains valid.','fix':'Replace assert acceptance with explicit exceptions; new aggregate runner requires fresh output, semantic success and unchanged source bytes.','status':'fixed and reproduced'},
 {'id':'C04','severity':'medium for proof metadata integrity','title':'Explicit unsafe theorem labels bypass the narrow blacklist','file':'round5/proof_search.py','lines':[201,204,231,238],'repro':'audit_repro.py: verification_proposed/conjectural/unsafe/unresolved; test_unsafe_node_verification_rejected','observed':'A declared theorem seed labeled proposed or unresolved is accepted and produces status proved.','impact':'Metadata inconsistency can be laundered into a trace. This does not show the accepted fixture has unsafe labels, nor can a text-label check establish theorem truth.','fix':'Reject the complete reserved unsafe label set after whitespace normalization. Mathematical rule certification remains an external review obligation.','status':'fixed and reproduced'},
 {'id':'C05','severity':'medium for reproducibility','title':'Referenced proof bytes are absent from the graph hash','file':'round5/proof_search.py','lines':[252,280],'repro':'test_external_proof_artifact_change_rejected; evidence_guard.py bound_plan','observed':'The library hash binds proof_ref strings, not bytes of the referenced theorem and contract documents. A changed document preserves the old library hash.','impact':'Stale external derivations could be displayed alongside a valid planning trace. This was a documented planner boundary, now additionally guarded.','fix':'New immutable-version evidence manifest binds fixture, planner and local referenced proof files; verify before/after planning, including unchanged manifest digest.','status':'provenance guard implemented and mutation tested'},
 {'id':'C06','severity':'low','title':'Exact large integer costs overflow during unnecessary float conversion','file':'round5/proof_search.py','lines':[61,67],'repro':'audit_repro.py: huge_cost; test_exact_large_integer_cost','observed':'Positive integer cost 10**400 raises OverflowError rather than following the documented integer-cost contract.','impact':'Input handling defect only; no wrong optimum for accepted ordinary-cost fixtures.','fix':'Keep positive Python integer costs exact; remove float conversion.','status':'fixed and reproduced'},
 {'id':'C07','severity':'medium for temporal diagnostics','title':'Missing observation windows can be reported as a pass; work window ignores overlapping pump','file':'round4/code/response.py','lines':[333,341],'repro':'test_no_causal_samples_does_not_pass_vacuously and test_work_constancy_waits_until_both_sources_stop','observed':'No pre-probe samples are assigned pre_max=0 and pass; no late samples return infinity. Work constancy is tested after the probe even if the primary pump remains active.','impact':'Vacuous causality pass or a false work-identity failure for a permitted pulse arrangement.','fix':'Report sample counts and null for unobserved windows; do not pass missing coverage. Begin post-drive work check only after both sources end.','status':'fixed and reproduced'},
 {'id':'C08','severity':'medium for scientific presentation','title':'Legacy conditional flag can be mistaken for an unconditional theorem','file':'round5/proof_search.py','lines':[507,517],'repro':'test_declared_conditions_are_distinct_from_conjectures; independently raised by physics skeptic','observed':'conditional:false means no explicitly retained conjecture, although finite-model hypotheses remain in assumptions.','impact':'A UI using only that flag could falsely label the result unconditional.','fix':'Emit declared_assumption_ids, conditional_on_declared_assumptions, conjectural_assumptions, conditional_flag_meaning and result_kind. Preserve old fields for compatibility.','status':'clarified and regression tested'},
 {'id':'C09','severity':'medium for provenance','title':'Scenario source hash was captured only after the computation','file':'round4/code/response.py; round5/run_checks.py','lines':[342,351,23,24],'repro':'test_source_changed_during_run_rejected','observed':'Historical source_hash() is evaluated at report assembly, so mid-run changes cannot be distinguished from a run of the reported source.','impact':'A general reproducibility gap; all 13 audited historical source/result/contract hashes currently match.','fix':'Capture source and imported legacy hashes before scenario execution, compare again before return. Aggregate gate checks its command source before/after execution.','status':'guard implemented and mutation tested'}]
notes={
 'round4/code/response.py':{'Grid.__init__':'Positive fixed quadrature, gauge node translation; new validation C02.','_validate':'Finite numeric/integer/positive checks; unsupported unrenormalized mode correctly rejected.','_chi':'Matched b=10 expression reviewed; no global floating-point enclosure or small-b accuracy claim.','_pulse':'Smooth compact pulse and endpoint support inspected.','_initial_state':'Fixed magnetic vacuum and zero amplitude tangent; gauge tangent v=1, deltaK=1. Arbitrary state families are not implemented.','_terms':'Per-mode subtraction and C,D definitions checked against contract and symbolic identities.','_tangent_terms':'Unused helper restricted to source-amplitude deltaK=0; reviewed separately; not an independent solver.','_closures':'Source construction C01/C02.','_solve':'Nested equations, work, raw diagnostics, NaN completeness checked; current uses u prime. Fixed small baseline equality; no intersample enclosure.','_solve.rhs':'Full quotient derivative, Bloch tangent, q=deltaK-v and work derivative checked against symbolic algebra.','run_scenario':'C01,C02,C07,C09; finite differences and gauge are preparation-specific.','write_csv':'Reviewed serialization; duplicate epsilon map overwrite prevented at scenario validation. CSV export itself not rerun.'},
 'round3/code/backreaction.py':{'_grid_terms':'Known legacy split-sum cancellation retained intentionally. No new fix retroactively claimed.','run':'Legacy comparator only; all macro keys inspected. No NaN completeness guard in this historical source. No fresh full trajectory acceptance.','run.rhs':'Matched branch compared; unrenormalized removes derivative subtraction consistently. Historical mode is not supported by new response tangent.','write_csv':'Static review only; zip truncates uneven arrays if caller supplies malformed arbitrary result; production result shapes are fixed.'},
 'round5/proof_search.py':{'_positive_integer':'C06.','load_library':'AND premises, scopes, assumption retention, statuses, frozen records checked; C04.','_library_hash':'Internal byte-canonical metadata hash correct; external-reference gap C05.','check_proof':'Every required premise is replayed; mutated library hash rejected; no implication reversal. Metadata does not substitute for a proof kernel.','_forward_uniform_cost':'Positive exact costs and goal-pop optimality reviewed. Scope is supplied finite rule library. Existing 24-test suite rerun on new engine.','_bidirectional_candidate':'First meeting is only an incumbent; independent forward pass certifies cost.','_backward_first_meeting':'Legacy unused helper; statically reviewed, not runtime exercised by current plan path.','plan':'Budget, blocked goal, not-derivable and conditional labels checked; C08.','main':'CLI serializes all supplied scenario results. A zero exit means execution succeeded, not every target proved; new acceptance runner checks required statuses.'},
 'round5/symbolic_checks.py':{'zero':'All 16 symbolic identities/mutants inspected and rerun in explicit-failure version; C03. This is not inequality, ODE existence or continuum proof.'},
 'round5/coefficient_certificate.py':{'main':'Frozen round4/round3 hashes, positive rounded weights/masses, rational mass grouping and bound checked. C03. Certificate encloses rational coefficients, not a floating trajectory/digamma analytic value.'},
 'round5/run_checks.py':{'main':'C03,C09. Original process output and six source hashes checked; new runner requires fresh semantic result.'}}
coverage=[]
for rel in FILES:
 p=PROJECT/rel;tree=ast.parse(p.read_text());entry={'file':rel,'sha256':sha(p),'line_count':len(p.read_text().splitlines()),'review':'All source text inspected, including module imports, constants, dataclasses, serialization and executable blocks. Static review is not exhaustive runtime coverage.','functions':[]}
 def walk(body,prefix=''):
  for n in body:
   if isinstance(n,ast.ClassDef):walk(n.body,prefix+n.name+'.')
   elif isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)):
    name=prefix+n.name;entry['functions'].append({'name':name,'start':n.lineno,'end':n.end_lineno,'review':notes.get(rel,{}).get(name,notes.get(rel,{}).get(n.name,'Static source review; covered by owning function/fixture where exercised.'))});walk(n.body,name+'.')
 walk(tree.body);coverage.append(entry)
newfiles={str(p.relative_to(PROJECT)):sha(p) for p in sorted((ROOT/'code').glob('*.py'))}
reg=json.loads((ROOT/'code_regression_results.json').read_text());compat=json.loads((ROOT/'planner_compatibility_results.json').read_text());hist=json.loads((ROOT/'historical_integrity_results.json').read_text())
report={'scope':'Selected 1,438 lines across six original computational files plus existing test/result artifacts; excludes dependencies, Site code, full repository, continuum physics and exhaustive dynamic/path coverage.','review_date':'2026-09-09','historical_sources_frozen':True,'finding_count':len(findings),'findings':findings,'coverage':coverage,'new_source_hashes':newfiles,'regression_tests':reg,'compatibility_tests':compat,'historical_integrity':hist,'scope_limits':['No fresh selected 1024-node trajectory or 2048-node refinement; historical sampled acceptance remains unchanged.','No interval enclosure between samples or proof of continuum regulator removal.','No arbitrary quantum-state tangent, finite-momentum response kernel, quantum noise or curved-spacetime pressure closure implemented.','A checked Horn trace and artifact hashes are not a formal theorem-assistant proof.','Small-b cancellation in the closed digamma expression and adversarial import/process compromise are outside the tested numerical domain.']}
(ROOT/'code_audit.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Round-six skeptical code audit','',report['scope'],'','The audit found nine concrete implementation or metadata issues. None changes the accepted default finite-model equation contract. The corrected small default fixture reproduces every historical macro diagnostic bit-for-bit. Historical sources were frozen; all repairs live in `round6/code/`.','','## What was reproduced and fixed','']
for f in findings:
 lines += [f"### {f['id']} — {f['title']}",'',f"**Severity/scope:** {f['severity']}. **Location:** `{f['file']}`; historical lines {', '.join(map(str,f['lines']))}.",'',f['observed'],'',f"**Impact:** {f['impact']}",'',f"**Correction:** {f['fix']}",'',f"**Executable evidence:** `{f['repro']}`. Status: {f['status']}.",'']
lines += ['## Measured corrections','', '| Check | Historical behavior | Round-six behavior |','|---|---|---|','| Nonzero delayed probe: finest derivative discrepancy | 2.9654e-5, stalled | 4.7009e-10 after second-order interval |','| Translated-gauge field difference, same probe | 0.5002586 from mismatched source | 2.7756e-14 |','| Default matched small fixture, every macro array | Reference | Exactly zero maximum difference |','| Wrong symbolic identity under python -O | Exit 0, passed false | Explicit nonzero exit |','| Recorded historical content hashes | 13 references | 13/13 still match |','',f"New targeted regression suite: **{reg['tests_run']}/{reg['tests_run']} passed**. Unchanged historical proof-planner suite run against the new engine: **24/24 passed**. These are separate checks, not 42 independent proofs of physics.",'','The finite-difference errors are 4.5900e-8, 5.0235e-9 and 4.7009e-10 for epsilon 0.03, 0.01 and 0.003. The measured ratio is compatible with the intended centered second-order check before a numerical floor. The test uses b=1, n=0, K=3, 12 longitudinal nodes and 61 time samples; it is a preparation regression, not a production refinement.','','## Function and line-span review matrix','','Each row denotes direct static review of the complete listed function. Nested rows name the important closures separately. This is not a runtime coverage percentage and does not claim that every possible branch was exercised. Module-level declarations and all 1,438 original source lines were also inspected.','']
for entry in coverage:
 lines += [f"### `{entry['file']}`",'',f"SHA-256: `{entry['sha256']}`. {entry['line_count']} lines.",'','| Function | Historical lines | Review / evidence boundary |','|---|---:|---|']
 for row in entry['functions']:lines.append(f"| `{row['name']}` | {row['start']}–{row['end']} | {row['review']} |")
 lines.append('')
lines += ['## Claims that remain outside this audit','','- The prior accepted trajectory uses 401 reported times at fixed K=20, n=0 through 4. Fixed-window quadrature refinement is distinct from either cutoff removal.','- The historical direct-current derivative discrepancy has its own reported values; the preselected field-tangent refinement threshold is not retroactively a current threshold.','- Pure-gauge validation translates potential and canonical nodes together. A potential shift at fixed nodes is a different finite regulator.','- The tangent solver supports source and gauge families prepared in the fixed vacuum. General initial-state and purity-changing families need a separate implementation contract.','- A constant or finite tangent is not a quantum noise or semiclassical-validity certificate.','- External proof-file hashes establish version integrity. They do not mechanically establish the mathematical correctness of the derivations.','','## Reproduce','','From the project directory:','','```sh','python round6/code/run_checks.py','```','','This executes 24 compatibility tests, the new regression suite, explicit-failure symbolic checks, the exact rounded-coefficient bound and the content-bound proof plan. It creates fresh result JSON and rejects failed semantic status even when a process exits zero. Dependencies are the existing NumPy/SciPy environment and SymPy 1.14 (the existing round5/deps directory is supported).','','All 13 inspected historical acceptance/validation hashes match in `historical_integrity_results.json`. The new source digests and complete function matrix are in `code_audit.json`. No historical source or result file was rewritten.']
(ROOT/'code_audit.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'findings':len(findings),'original_lines':sum(x['line_count'] for x in coverage),'functions':sum(len(x['functions']) for x in coverage),'regression_tests':reg['tests_run'],'compatibility_tests':compat['tests_run']}))
