import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url),base=new URL('dist/',root),records=new URL('research/round12/',root),nodes=new Map(),events={},checks=[];
const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',open:false,value:'',focus(){},showModal(){this.open=true},close(){this.open=false},querySelector(){return node('close')},addEventListener(){}});return nodes.get(id);};
const ctx={console,URL,Blob,setTimeout:()=>0,location:{hash:'#research'},localStorage:{getItem(){return null},setItem(){}},document:{querySelector:node,getElementById:id=>node('#'+id),addEventListener:(e,f)=>(events[e]??=[]).push(f)},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);
const html=fs.readFileSync(new URL('index.html',base),'utf8');
const scripts=[...html.matchAll(/<script src="(research[^\"]*\.js)"/g)].map(x=>x[1]);
// Test the preserved round12 overlay; current round13 integration has its own suite.
for(const name of scripts.filter(name=>!name.startsWith('research-next')&&!name.startsWith('research-six')&&!name.startsWith('research-shared')&&!name.startsWith('research-exceptions')&&!name.startsWith('research-team')&&!name.startsWith('research-cycles')))vm.runInContext(fs.readFileSync(new URL(name,base),'utf8'),ctx,{filename:name});
const D=ctx.OBSERVATORY_BRIDGES,T=ctx.ResearchObservatory;
const pages=['home','dynamic-proof','exact-evolution','dynamic-experiments','volume-bridge','closure-audit','bridge-variables','bridge-roadmap','bridge-review'];
function check(name,fn){fn();checks.push({name,passed:true});}
const read=p=>{const path=new URL(p,records);return JSON.parse(fs.existsSync(path)?fs.readFileSync(path,'utf8'):gunzipSync(fs.readFileSync(new URL(p+'.gz',records))).toString('utf8'));};
const csv=name=>{const lines=fs.readFileSync(new URL(name,base),'utf8').trim().split(/\r?\n/),heads=lines.shift().split(',');return lines.map(line=>Object.fromEntries(line.split(',').map((x,i)=>[heads[i],x])));};
const rational=s=>{const [a,b='1']=String(s).split('/');return Number(a)/Number(b);};
// Python and JavaScript log10 may differ by a few rounding units; raw x values remain exact.
const logPoint=(actual,expected)=>{assert.equal(actual[0],expected[0]);assert(Number.isFinite(actual[1])&&Number.isFinite(expected[1]));assert(Math.abs(actual[1]-expected[1])<=8*Number.EPSILON*Math.max(1,Math.abs(expected[1])));};
check('Nine new routes, correct titles and historical research remain reachable',()=>{for(const page of pages){ctx.location.hash='#research/'+page;const h=T.render(page);assert.equal((h.match(/<h1>/g)||[]).length,1);assert(h.includes('aria-current="page"'));T.afterRender();assert(ctx.document.title.includes('Yang–Mills'));for(const match of h.matchAll(/href="#research\/([^"]+)"/g))assert(!T.render(match[1]).includes('Research page not found'),match[1]);}assert(T.render('review11-home').includes('Historical round11'));for(const p of ['constructor','__proto__','missing'])assert(T.render(p).includes('Research page not found'));});
check('Exact and floating result boundaries are visible on the relevant pages',()=>{assert(T.render('dynamic-proof').includes('D−d₀+1'));assert(T.render('dynamic-experiments').includes('1/3840'));assert(T.render('dynamic-experiments').includes('uninformative'));assert(T.render('exact-evolution').includes('27/80000'));assert(T.render('exact-evolution').includes('not renormalized'));assert(T.render('volume-bridge').includes('disconnected'));assert(T.render('closure-audit').includes('rank is at most 4'));assert(T.render('home').includes('still open'));});
check('Stored exact vector and total error are the unmodified reviewed certificate',()=>{const original=read('solver/output/exact_step_certificate.json');assert.deepEqual(JSON.parse(D.documents.exact),original);assert.equal(original.final_coefficients.length,20);assert.equal(original.computed_vector_was_renormalized,false);const [a,b='1']=original.total_state_error_upper.split('/');assert(BigInt(a)*1000000000n<337501n*BigInt(b));assert.equal(D.exactSummary.total,original.total_state_error_upper);});
check('Reduced drive plot is bound to every positive recorded datum without a log floor',()=>{const rows=csv('bridge-drive-bounds.csv');let i=0;for(const d of [3,4])for(const field of ['analytic_error_upper','empirical_D6_difference']){const selected=rows.filter(r=>r.case==='reduced'&&Number(r.degree)===d&&rational(r[field])>0);const actual=D.plots.drive_bound.series[i++].points;assert.equal(actual.length,selected.length);selected.forEach((r,j)=>logPoint(actual[j],[rational(r.time),Math.log10(rational(r[field]))]));}});
check('Equal-action comparison preserves all three physical durations',()=>{const rows=csv('bridge-drive-summary.csv').filter(r=>['reduced','short','slow'].includes(r.case)&&r.degree==='4');for(const [i,field] of ['analytic_state_error_upper','empirical_final_D6_difference'].entries()){const expected=rows.map(r=>[rational(r.duration),Math.log10(rational(r[field]))]).sort((a,b)=>a[0]-b[0]);assert.equal(D.plots.drive_action.series[i].points.length,expected.length);expected.forEach((p,j)=>logPoint(D.plots.drive_action.series[i].points[j],p));}assert.deepEqual(Array.from(D.plots.drive_action.series[0].points,p=>p[0]),[.2,2,4]);});
check('Volume and tensor graphs retain logarithms and distinct certified/diagnostic labels',()=>{const tensor=csv('bridge-tensor.csv');const p=D.plots.volume_tensor;assert(p.series[1].name.includes('numerical'));tensor.forEach((r,i)=>assert.deepEqual(Array.from(p.series[2].points[i]),[Number(r.q_independent_copies),Number(r.global_one_square_log10_comparison)]));const box=csv('bridge-volume.csv');for(const [x,y] of D.plots.volume_box.series[0].points)assert(box.some(r=>Number(r.n_cells_per_side)===x&&Number(r.log10_bound_Delta_over_alpha)===y));assert(D.plots.volume_box.caption.includes('underflow'));});
check('Closure graph binds the signed residual and retains the blind zero-coupling case',()=>{const rows=csv('bridge-closure.csv');for(const [i,field] of ['true_residual','collapsed_residual'].entries())rows.forEach((r,j)=>assert.deepEqual(Array.from(D.plots.closure.series[i].points[j]),[Number(r.kappa),Number(r[field])]));assert(rows.some(r=>Number(r.kappa)===0));assert(T.render('closure-audit').includes('the next forces m₂=1/4'));});
check('Incomplete or nonfinite plot records fail visibly',()=>{const saved=D.plots.closure;for(const series of [null,[],[null],[{points:[]}],[{points:[[0,NaN]]}],[{points:'missing'}]]){D.plots.closure={series};assert(ctx.ResearchBridges.plot('closure').includes('No completed'));}D.plots.closure=saved;});
check('Every advertised document and download resolves; labels escape markup',()=>{for(const p of pages){const h=T.render(p);for(const m of h.matchAll(/data-r-doc="([^"]+)"/g))assert(ctx.OBSERVATORY_RESEARCH.documents[m[1]]?.length>30,m[1]);for(const m of h.matchAll(/href="\/([^"?]+)" download/g))assert(fs.existsSync(new URL(m[1],base)),m[1]);}const old=D.roadmap[0].title;D.roadmap[0].title='<img src=x onerror=alert(1)>';assert(!T.render('bridge-roadmap').includes('<img'));D.roadmap[0].title=old;});
check('Compact proof dialog preserves certificates and assumptions with full traces available separately',()=>{const full=read('proof_results.json'),compact=JSON.parse(D.documents.routes);assert.equal(compact.status,full.status);assert.deepEqual(compact.manifest,full.manifest);assert(compact.trace_storage.includes('omits'));for(const [name,route] of Object.entries(full.routes)){assert.deepEqual(compact.routes[name].library,route.library);const expected=Object.fromEntries(Object.entries(route.result).filter(([key])=>!['search_trace','frontier'].includes(key)));assert.deepEqual(compact.routes[name].result,expected);}assert(fs.statSync(new URL('research-bridges-data.js',base)).size<2000000);assert(fs.existsSync(new URL('research-round12-proof-trace.json.gz',base)));});
check('Current roadmap reconciles prior proposals and keeps full-theory dependencies blocked',()=>{const r=read('current_roadmap.json');assert.equal(D.roadmap.length,r.items.length);assert(D.roadmap.find(x=>x.id==='R11-X04').status.includes('completed'));assert(D.roadmap.find(x=>x.id==='NEXT-CONTINUUM').status==='open');const proof=read('proof_results.json');assert.equal(proof.routes.exact_piecewise_computed_state.result.status,'proved');for(const name of ['cosine_total_error_unavailable','without_degree_bandwidth','without_initial_support','without_absolute_action','without_exact_vector_replay','four_dimensional_yang_mills'])assert.equal(proof.routes[name].result.status,'not_derivable');});
const result={status:'passed',count:checks.length,checks,scope:'Node VM routes, evidence/CSV bindings, escaping and data failure states. No real-browser visual audit.'};
fs.writeFileSync(new URL('site-validation.json',records),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
