// Recorded data, route and event checks in a DOM stand-in. No browser QA claim.
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const base=new URL('../dist/',import.meta.url),events={},nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',open:false,value:'',focus(){},showModal(){this.open=true},close(){this.open=false},querySelector(){return node('close')},addEventListener(){}});return nodes.get(id);}
const ctx={console,URL,Blob,setTimeout:()=>0,location:{hash:'#research'},localStorage:{getItem(){return null},setItem(){}},document:{querySelector:node,getElementById:id=>node('#'+id),addEventListener:(e,fn)=>(events[e]??=[]).push(fn)},addEventListener(){}};
ctx.window=ctx;vm.createContext(ctx);
const files=['research-data.js','research.js','research-hub-data.js','research-hub.js','research-closures-data.js','research-closures.js'];
for(const file of files)vm.runInContext(fs.readFileSync(new URL(file,base),'utf8'),ctx,{filename:file});
const D=ctx.OBSERVATORY_CLOSURES,T=ctx.ResearchObservatory,checks=[];
const check=(name,fn)=>{fn();checks.push({name,passed:true});};
const fire=(type,target)=>{for(const fn of events[type]||[])fn({target});};
check('Home retains the foundation and exposes current scoped closures',()=>{const h=T.render();assert.equal((h.match(/<h1>/g)||[]).length,1);for(const x of ['Current extension','Earlier foundation','42','47','regulator-dependent','remain open'])assert(h.includes(x),x);assert(h.includes('Review 7'));});
check('Five dedicated routes and inherited unknown-page recovery',()=>{for(const p of ['variables','finite','gravity','cutoff','proofs']){ctx.location.hash='#research/'+p;const h=T.render(p);assert.equal((h.match(/<h1>/g)||[]).length,1,p);assert(h.includes('aria-current="page"'));assert(!h.includes('NaN'));assert(!h.includes('undefined'));T.afterRender();assert(ctx.document.title.includes('Physics Observatory'));}for(const p of ['unknown','__proto__','constructor'])assert.match(T.render(p),/page not found/);});
check('Evidence gate counts and complete case suite are grounded in JSON',()=>{assert.equal(D.root.status,'passed');assert.equal(D.root.passed_checks,47);assert.equal(D.root.checks.filter(c=>c.passed).length,47);assert.equal(D.critic.passed_checks,42);assert.equal(D.gravity.cases.length,8);assert(D.gravity.analytic_fixtures.passed);assert.equal(D.finite.gates.g0_baseline.status,'compared');});
check('Proof routes retain exact scopes, costs, missing certificates and no seeded numerical evidence',()=>{for(const [key,n] of [['finite_continuation',17],['gravity_constraint',11],['reference_coefficient',4],['bounded_addition_obstruction',4]]){const x=D.routes[key];assert.equal(x.result.certified_cost,n);assert.equal(x.result.certified_proof.steps.length,n);assert(x.result.conditional_on_declared_assumptions);for(const id of x.library.initial_facts)assert.notEqual(x.library.nodes.find(n=>n.id===id).kind,'numerical_evidence');}for(const key of ['common_quantum_closure','missing_Maxwell_certificate']){assert.equal(D.routes[key].result.status,'not_derivable');assert.equal(D.routes[key].library.blocked_goals.length,0);}});
check('Every plotted sample comes from the shipped CSV',()=>{for(const [key,p] of Object.entries(D.plots)){const lines=fs.readFileSync(new URL(p.csv.slice(1),base),'utf8').trim().split(/\r?\n/);const heads=lines.shift().split(',');const rows=lines.map(l=>Object.fromEntries(l.split(',').map((v,i)=>[heads[i],v])));let source=rows;if(key==='gravity')source=rows.filter(r=>r.case==='coupled_mixed');const fields=key==='finite'?['x','phi']:key==='work'?['energy_mismatch','energy_mismatch']:['C_full','C_wrong'];for(let i=0;i<p.series.length;i++){let r=source;if(key==='work'&&i===0){const l=fs.readFileSync(new URL('finite_correct.csv',base),'utf8').trim().split(/\r?\n/);const h=l.shift().split(',');r=l.map(line=>Object.fromEntries(line.split(',').map((v,j)=>[h[j],v])));}assert.equal(p.series[i].points.length,r.length);for(let j=0;j<r.length;j++){assert.equal(p.series[i].points[j][0],Number(r[j][key==='gravity'?'tau':'t']));assert.equal(p.series[i].points[j][1],Number(r[j][fields[i]]));}}assert(ctx.ResearchClosures.plot(key).includes('CSV'));}});
check('Invalid plot data is explicit and never silently repaired',()=>{assert.match(ctx.ResearchClosures.plot('unknown'),/No valid recorded/);const p=D.plots.finite;for(const series of [[],[null],[{points:[[0,NaN]]}],[{points:[]} ]]){D.plots.finite={series};assert.match(ctx.ResearchClosures.plot('finite'),/No valid recorded/);}D.plots.finite=p;});
check('Variable search supports an empty result and safely escapes values',()=>{fire('input',{id:'closure-variable-search',value:'no_such_variable_9824'});assert.match(node('#closure-variable-results').innerHTML,/No variables match/);fire('input',{id:'closure-variable-search',value:'pressure'});assert(node('#closure-variable-results').innerHTML.includes('pressure'));fire('input',{id:'closure-variable-search',value:''});assert(node('#closure-variable-results').innerHTML.includes('18 of 18'));D.variables.push({symbol:'<img src=x onerror=alert(1)>',type:'test'});fire('input',{id:'closure-variable-search',value:'onerror'});assert(!node('#closure-variable-results').innerHTML.includes('<img'));D.variables.pop();fire('input',{id:'closure-variable-search',value:''});});
check('Proof and plot selectors render only known recorded keys',()=>{fire('change',{id:'closure-route',value:'common_quantum_closure'});assert.match(node('#closure-route-view').innerHTML,/Not derivable/);assert.match(node('#closure-route-view').innerHTML,/No reviewed sufficient/);fire('change',{id:'closure-route',value:'finite_continuation'});assert.equal((node('#closure-route-view').innerHTML.match(/<li>/g)||[]).length,17);const before=node('#closure-route-view').innerHTML;fire('change',{id:'closure-route',value:'__proto__'});assert.equal(node('#closure-route-view').innerHTML,before);fire('change',{id:'closure-plot',value:'gravity'});assert.match(node('#closure-plot-view').innerHTML,/Bianchi/);});
check('New full notes open through the existing escaped explicit dialog',()=>{assert(ctx.OBSERVATORY_RESEARCH.documents['round7/variable_contract.md']);const b={dataset:{rDoc:'round7/variable_contract.md'},hasAttribute:()=>false};fire('click',{closest:s=>s.includes('[data-r-doc]')?b:null});assert(node('#research-dialog').open);assert.match(node('#research-body').innerHTML,/F2/);assert(!node('#research-body').innerHTML.includes('<script'));});
check('Scientific limitations are present on each relevant page',()=>{assert.match(T.render('finite'),/does not prove convergence/);assert.match(T.render('gravity'),/no Dirac field/);assert.match(T.render('cutoff'),/common state\/current\/stress/);assert.match(T.render('proofs'),/not checked by a mathematical proof kernel/);assert.match(T.render('variables'),/reached a usage limit/);});
check('Current section survives historical technical-mode rerender',()=>{ctx.location.hash='#research';fire('click',{closest:s=>s==='[data-hub-mode]'?{dataset:{hubMode:'technical'}}:null});assert.match(node('#main').innerHTML,/Current extension/);assert.match(node('#main').innerHTML,/Earlier foundation/);});
check('Sources and downloadable report are available',()=>{assert.equal(D.sources.length,19);for(const s of D.sources){assert(s.title);assert.equal(new URL(s.url).protocol,'https:');}assert.match(T.render('variables'),/Primary references/);assert(fs.readFileSync(new URL('einstein-qed-variable-study.pdf',base)).subarray(0,5).equals(Buffer.from('%PDF-')));assert(fs.existsSync(new URL('closure-proof-map.json',base)));});
const out={passed:true,checks,scope:'VM render and event tests, recorded CSV binding and evidence semantics; no browser layout or end-to-end claim.',source_sha256:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(new URL(f,base))).digest('hex')]))};
fs.writeFileSync(new URL('../research-closures-validation.json',import.meta.url),JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({passed:true,checks:checks.length,scope:out.scope}));
