import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url),base=new URL('dist/',root),records=new URL('research/round11/',root),events={},nodes=new Map(),checks=[];
function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',open:false,value:'',focus(){},showModal(){this.open=true},close(){this.open=false},querySelector(){return node('close')},addEventListener(){}});return nodes.get(id);}
const ctx={console,URL,Blob,setTimeout:()=>0,location:{hash:'#research'},localStorage:{getItem(){return null},setItem(){}},document:{querySelector:node,getElementById:id=>node('#'+id),addEventListener:(e,f)=>(events[e]??=[]).push(f)},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);
const files=['research-data.js','research.js','research-hub-data.js','research-hub.js','research-closures-data.js','research-closures.js','research-millennium-data.js','research-millennium.js','research-yangmills-data.js','research-yangmills.js','research-plaquette-data.js','research-plaquette.js','research-two-plaquette-data.js','research-two-plaquette.js'];for(const file of files)vm.runInContext(fs.readFileSync(new URL(file,base),'utf8'),ctx,{filename:file});
const D=ctx.OBSERVATORY_TWO_PLAQUETTE,T=ctx.ResearchObservatory;
function check(name,fn){fn();checks.push({name,passed:true});}
const pages=['home','two-model','two-spectrum','two-gap','two-certificates','two-dynamics','two-roadmap','two-review'];
check('Eight current routes and previous homes are reachable',()=>{for(const p of pages){ctx.location.hash='#research/'+p;const html=T.render(p);assert.equal((html.match(/<h1>/g)||[]).length,1,p);assert(html.includes('aria-current="page"'));T.afterRender();for(const m of html.matchAll(/href="#research\/([^"]+)"/g))assert(!T.render(m[1]).includes('Research page not found'),m[1]);}assert(T.render('review10-home').includes('controlled interaction'));for(const p of ['__proto__','constructor','bad-route'])assert(T.render(p).includes('Research page not found'));});
check('Critical mathematical boundaries are visible',()=>{assert(T.render('two-spectrum').includes('K(xy)=13xy/2−z/2'));assert(T.render('two-model').includes('κ₊≥|κ₋|'));assert(T.render('two-model').includes('not a claimed singularity'));assert(T.render('two-gap').includes('243/625'));assert(T.render('two-certificates').includes('0.96'));assert(T.render('two-dynamics').includes('0.0040908195'));assert(T.render('home').includes('four-dimensional'));});
const original=JSON.parse(fs.readFileSync(new URL('solver/output/stationary_certificates.json',records),'utf8')).certificates;
check('Every displayed exact certificate matches the original full rational record',()=>{assert.equal(D.certificates.length,8);D.certificates.forEach((c,i)=>{assert.deepEqual(JSON.parse(D.documents[c.document]),original[i]);assert(c.display.includes(original[i].gap[0]));assert(c.display.includes(original[i].gap[1]));});});
check('Selection changes the certificate and unknown values fall back safely',()=>{for(const fn of events.change)fn({target:{id:'t11-certificate',value:'7'}});assert(node('#t11-detail').innerHTML.includes(D.certificates[7].label));for(const fn of events.change)fn({target:{id:'t11-certificate',value:'__proto__'}});assert(node('#t11-detail').innerHTML.includes(D.certificates[0].label));});
const csv=name=>{const text=fs.readFileSync(new URL(name,base),'utf8').trim().split(/\r?\n/),h=text.shift().split(',');return text.map(l=>Object.fromEntries(l.split(',').map((v,i)=>[h[i],v])));};
check('Convergence plot omits uncomputed intervals and binds every displayed endpoint',()=>{const data=csv('two-convergence.csv');for(const [i,field] of ['gap_Ritz_estimate','gap_certified_lower','gap_certified_upper'].entries()){const rows=data.filter(r=>r[field]!=='');assert.equal(D.plots.convergence.series[i].points.length,rows.length);rows.forEach((r,j)=>assert.deepEqual(Array.from(D.plots.convergence.series[i].points[j]),[Number(r.degree),Number(r[field])]));}assert.equal(D.plots.convergence.series[1].points.length,3);});
check('Each parameter has its own labeled sweep and recorded coefficient values',()=>{const data=csv('two-sweeps.csv');assert.equal(D.sweepKeys.length,4);for(const key of D.sweepKeys){const axis=key.replace('sweep_',''),rows=data.filter(r=>r.axis===axis);rows.forEach((r,i)=>assert.deepEqual(Array.from(D.plots[key].series[0].points[i]),[Number(r.value),Number(r.gap_Ritz_estimate)]));}});
check('Driven energy and independent work retain every raw time sample',()=>{const data=csv('two-drive.csv');for(const [i,field] of ['energy','integrated_work'].entries())data.forEach((r,j)=>assert.deepEqual(Array.from(D.plots.drive.series[i].points[j]),[Number(r.t),Number(r[field])]));assert(Number(data.at(-1).energy)>4);assert(Math.abs(Number(data.at(-1).work_defect))<1e-9);});
check('Malformed plot series cannot appear as completed data',()=>{const saved=D.plots.drive;for(const series of [[],[null],'bad',[{points:'bad'}],[{points:[[0,NaN]]}]]){D.plots.drive={series};assert(ctx.ResearchTwoPlaquette.plot('drive').includes('No completed'));}D.plots.drive=saved;});
check('All documents and downloads exist and titles escape markup',()=>{for(const page of pages){const html=T.render(page);for(const m of html.matchAll(/data-r-doc="([^"]+)"/g))assert(ctx.OBSERVATORY_RESEARCH.documents[m[1]]?.length>30,m[1]);for(const m of html.matchAll(/href="\/([^"?]+)" download/g))assert(fs.existsSync(new URL(m[1],base)),m[1]);}const saved=D.certificates[0].label;D.certificates[0].label='<img src=x onerror=alert(1)>';assert(!ctx.ResearchTwoPlaquette.selected().includes('<img'));D.certificates[0].label=saved;});
check('Thirty-seven claims and all blocked full-theory routes remain explicit',()=>{assert.equal(D.nodes.length,37);const proof=JSON.parse(fs.readFileSync(new URL('proof_results.json',records),'utf8'));assert.equal(proof.routes.certified_rectangle.result.certified_cost,17);assert.equal(proof.routes.analytic_all_finite.result.certified_cost,13);for(const [name,r] of Object.entries(proof.routes))if(name.startsWith('without')||name==='yang_mills_prize')assert.equal(r.result.status,'not_derivable');});
const report={status:'passed',count:checks.length,checks,scope:'Node VM routes, events, model text and recorded plot bindings; no real-browser visual audit.'};fs.writeFileSync(new URL('site-validation.json',records),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
