from pathlib import Path
import json, hashlib
root=Path(__file__).parent
sources=[
('S01','Yang-Mills & the Mass Gap','Clay Mathematics Institute','https://www.claymath.org/millennium/yang-mills-the-maths-gap/','live page checked 2026-09-09',None,'Full status/overview text','Official current unsolved status','Status page is not a proof audit.'),
('S02','Quantum Yang-Mills Theory','Arthur Jaffe; Edward Witten','https://www.claymath.org/wp-content/uploads/2022/06/yangmills.pdf','official problem formulation',None,'Sections 1–5, especially Section 4; regulator discussion inherited from round12','Required target: nontrivial four-dimensional pure theory and physical spectral gap','Historical overview is not a current literature census.'),
('S03','Quasi-Locality Bounds for Quantum Lattice Systems. Part I. Lieb-Robinson Bounds, Quasi-Local Maps, and Spectral Flow Automorphisms','Bruno Nachtergaele; Robert Sims; Amanda Young','https://arxiv.org/html/1810.02428v2','v2','2019-03-01','Introduction; Sections 2.3, 3.1–3.3; Theorems 3.3–3.5 and Corollary 3.6; selected recursive proof','Unbounded on-site terms and bounded interactions; topology distinctions; boundary estimates','Selected sections, not a complete 106-page audit. Project constants require independent derivation. HTML rendering date is not version date.'),
('S04','Bootstrap for Finite N Lattice Yang-Mills Theory','Vladimir Kazakov; Zechuan Zheng','https://arxiv.org/html/2404.16925v4','v4','2024-12-04','Sections 1–3; SU(2) trace relation; moment positivity; hierarchy description','Finite-N trace identities and positive observable matrices','No numerical optimizer or published certificate independently replayed here; finite hierarchy is not full continuum construction.'),
('S05','A stochastic analysis approach to lattice Yang--Mills at strong coupling','Hao Shen; Rongchan Zhu; Xiangchan Zhu','https://arxiv.org/pdf/2204.12737','v1','2022-04-27','Abstract/version; main assumptions; selected Hessian and functional-inequality discussion; detailed normalization inherited from round12 volume review','Strong-coupling fixed-spacing scope and beta normalization','Not a real-time Hamiltonian gap proof or weak-coupling continuum limit.'),
('S06','Center-stabilized Yang-Mills theory: confinement and large N volume independence','Mithat Unsal; Laurence G. Yaffe','https://arxiv.org/pdf/0803.0344','v2','2008-03-22','Abstract; Section 2 action/center symmetry/volume independence; selected Section 3 monopole-gas description','Concrete deformation parameters and compactification route','Semiclassical and large-N statements have separate assumptions; no independent uniform decompactification proof here.'),
('S07','Closed formula for Wilson loops for SU(N) Quantum Yang-Mills Theory in two dimensions','Abhay Ashtekar; Jurek Lewandowski; Donald Marolf; José Mourão; Thomas Thiemann','https://arxiv.org/abs/hep-th/9605128v1','v1','1996-05-18','Abstract, comments, publication/version metadata','Rigorous 2D model as scoped reconstruction benchmark','Abstract scope only; full proof not reviewed.'),
('S08','Invariant measure and universality of the 2D Yang-Mills Langevin dynamic','Ilya Chevyrev; Hao Shen','https://arxiv.org/abs/2302.12160v3','v3','2026-04-06','Abstract and version/publication history','Current 2D torus trivial-bundle universality result','Abstract scope only; 165-page proof not audited.'),
('S09','Stochastic quantisation of Yang-Mills-Higgs in 3D','Ajay Chandra; Ilya Chevyrev; Martin Hairer; Hao Shen','https://arxiv.org/abs/2201.03487v2','v2','2024-04-15','Abstract and version/publication history','Local stochastic-time YMH construction and possible blow-up','Additional fields, changed dimension; full proof not audited.'),
('S10','Uniqueness of gauge covariant renormalisation of stochastic 3D Yang-Mills-Higgs','Ilya Chevyrev; Hao Shen','https://arxiv.org/abs/2503.03060v2','v2','2026-01-21','Abstract and version/publication history','Uniqueness of gauge-covariant renormalization in specified 3D model','Counterterm is not a freely inserted physical gauge-boson mass.'),
('S11','Scaling limit of the 3D abelian Yang--Mills Langevin dynamics','Ilya Chevyrev; Yahui Qu; Hao Shen','https://arxiv.org/abs/2608.27828v1','v1','2026-08-28','Abstract and submission history','Recent Abelian weak-coupling local stochastic-time scaling','Abelian and 3D; no nonabelian 4D gap implication.'),
('S12','Properties and uses of the Wilson flow in lattice QCD','Martin Lüscher','https://arxiv.org/abs/1006.4518v3','v3','2014-01-27','Abstract, corrected-code note, version history','Flow time as smoothing scale; importance of corrected analysis versions','Not a physical-time evolution or a proof of the Yang-Mills gap. No code replay.')]
sources.append(('S13','Quasi-particles in weak perturbations of non-interacting quantum lattice systems','D. A. Yarotsky','https://arxiv.org/pdf/math-ph/0411042','v1','2004-11-11','Definitions and Theorems 1–3, pp.2–4; selected Section 2 expansion and references 23–24','Infinite-dimensional on-site product-vacuum gap stability with bounded finite-range perturbations','Existential smallness constants only; full cluster expansion not independently rebuilt; quasiparticle results not imported.'))
rows=[]
for sid,title,authors,url,version,date,depth,supports,limits in sources:
 rows.append(dict(id=sid,title=title,authors=authors,url=url,version=version,version_date=date,accessed='2026-09-09',reading_depth=depth,supports=supports,limitations=limits,source_type='primary'))
(root/'sources.json').write_text(json.dumps(dict(scope='Targeted primary-source review for round13; no exhaustive-literature claim.',primary_sources=rows),indent=2,ensure_ascii=False)+'\n')
cases=[
('C01','SU(2) trace identity','scope-preserving exact algebra','trace count','Cayley–Hamilton for SU(2)','Products of traces reduce to traces of concatenated or reversed loops.','Finite loop length and expectation factorization remain unproved.','Test normalized traces at U=V=I and noncommuting matrices.',['S04']),
('C02','Interaction picture','scope-preserving exact transformation','free electric phase','Self-adjoint on-link generators; bounded local plaquette interactions','Eliminates unbounded on-link operators from propagation-norm estimates.','Does not remove electric dynamics or create a gap.','Check support and norms; reject a transformed term on the wrong links.',['S03']),
('C03','Moment and variance variables','scope-preserving observable hierarchy','m_n, variance, hierarchy order','One specified positive compact measure','Necessary inequalities bound missing moments.','Finite feasibility does not identify the measure or ground state.','Exact recurrence, support localizer, rational exclusion and kappa-zero controls.',['S04']),
('C04','Zero tilt','scope-preserving parameter exception','kappa_E=0','Haar branch of the finite one-plaquette measure','Exact Catalan moments and variance 1/4.','The first force identity alone is blind to the variance.','Do not divide by kappa; test next recurrence.',[]),
('C05','Tree without charges','changed graph, trivial physical sector','cycle count zero','Finite connected tree; Gauss law at every vertex; no charges','Only the constant gauge-invariant state survives.','No nontrivial excitation or four-dimensional theory is obtained.','Explicit tree gauge reduction and charged-boundary mutant.',[]),
('C06','Short cycles or changed boundary charges','changed graph or sector','girth; external representation','Actual incidence and boundary Gauss constraints','Free physical energy threshold must be recalculated.','Square-graph gap constant cannot be imported.','Triangle/parallel-edge/open-charge minimal counterexamples.',[]),
('C07','Strong-coupling infinite lattice','restricted regime','beta_SZ','SU(N): abs(beta_SZ)<1/[16(d-1)]','Uniform stochastic/Euclidean estimates at fixed lattice spacing.','Weak-coupling continuum path leaves that sufficient regime.','Translate beta_W=N^2 beta_SZ; keep generator types separate.',['S05']),
('C08','Exact two-dimensional theory','changed dimension','D=2','Specified groups and spacetime topology','Controlled Wilson loops and reconstruction benchmark.','Dimensional extrapolation does not prove D=4.','Retain dimension, topology and local-observable content.',['S07','S08']),
('C09','Three-dimensional stochastic theory','changed dimension and possibly field content','D=3; stochastic time; counterterms','Each source-specific gauge group, state space and local existence assumptions','Renormalization and approximation lessons.','Not physical-time pure nonabelian four-dimensional construction.','Separate Higgs and Abelian branches and possible finite-time blow-up.',['S09','S10','S11']),
('C10','Center-stabilized compactification','changed action and geometry','circle circumference L_c; a_n; N','Center symmetry; declared double-trace deformation; controlled small-circle/large-N regime','A concrete calculable deformation route.','Removing deformation and decompactifying need uniform estimates and no unjustified interchange of limits.','Track center symmetry, approximation remainder and finite-N spectrum along the path.',['S06']),
('C11','Exact auxiliary field','conditionally scope-preserving representation','auxiliary field and integration contour','An exact convergent integral identity reproduces measure and observables','Alternative representation of the same theory.','Approximate elimination or changed Jacobian changes the theory.','Integrate auxiliary field out and recover the original finite measure exactly.',[]),
('C12','New physical mass or Higgs field','changed action and field content','new mass or field','Specified gauge-invariant action and state','Defines a different theory with a possible different mass mechanism.','Does not solve the original pure-gauge problem without a removal/equivalence theorem.','Show actual action, stress/energy and decoupling limit.',['S02','S09']),
('C13','Flow time','observable smoothing parameter','tau_f>0','Specified gauge-covariant flow and renormalized observables','Defines smoothed gauge observables and a scale.','It is not real time or a generated spectral mass.','Keep flow-time, physical-time and lattice-spacing limits separate.',['S12']),
('C14','Running coupling and physical units','scope-preserving only with matching','g(a), a, L=n a','A derived or fitted renormalization prescription is declared','Rewrites the regulator path in common variables.','A freely chosen g(a) is only a diagnostic path.','Retain alpha=g_H^2/(2a), lambda=2/(g_H^2 a), and all exposed a dependence.',[]),
('C15','Zero interaction and vanishing electric scale','parameter edge with possible singular spectral limit','lambda=0 or alpha->0','Fixed graph and normalization','Lambda-zero local influence vanishes; alpha positivity assumptions can fail in a limit.','An alpha-independent locality bound is not an alpha-independent gap bound.','Compare independent links and explicit small-energy excitations.',[])]
cases.append(('C16','Weak plaquette perturbation of electric product vacuum','scope-preserving restricted static regime','kappa_H=lambda_max/alpha; existential kappa_star','Infinite-dimensional gapped on-site blocks; static finite-range bounded plaquette interactions; matched empty boundary or proved padding; eta<c1 and c2 eta<1/2','An actual volume-uniform full and Gauss-restricted Hamiltonian gap at fixed spacing for sufficiently small kappa_H.','No evaluated numerical threshold; weak-bare-coupling continuum path kappa_H=4/g_H^4 exits the sufficient regime.','Reject finite-dimensional-only source substitutions, unproved boundary transfer, missing smallness, numerical kappa-star claims and ground-state sector mismatch.',['S13']))
items=[]
for cid,name,kind,var,premise,result,gap,test,src in cases:
 items.append(dict(id=cid,title=name,classification=kind,variables=var,assumptions=premise,legitimate_use=result,unresolved_bridge=gap,rejection_test=test,sources=src,status='reviewed route classification; no new simulation implied'))
(root/'case_matrix.json').write_text(json.dumps(dict(version='round13-cases-v1',cases=items),indent=2,ensure_ascii=False)+'\n')
claims=[
('link_tensor','Finite link Hilbert spaces form a tensor product before Gauss projection.','contract'),
('onsite_selfadjoint','The free electric generator is self-adjoint on its natural domain and the compared regions share identical on-link generators and coefficients through a common tensor embedding.','contract'),
('bounded_plaquettes','After scalar removal, all plaquette norms admit one common locally integrable absolute envelope on each compact time interval; compared regions use identical retained interaction coefficients.','derived'),
('bounded_incidence','The plaquette incidence constant is uniform across the selected graph family, and the tested bounded observable has one fixed finite support.','contract'),
('interaction_picture','Free on-link conjugation preserves interaction support and norm.','derived'),
('path_count','A reviewed explicit chain count and ordered-time integral bound hold.','implementation gate'),
('local_commutator_bound','The declared bounded local commutator obeys the certified locality bound.','conditional'),
('boundary_shell_sum','A nested exhaustive region family with matching retained coefficients has omitted-boundary distance tending to infinity from the fixed finite observable support; the reviewed tail tends to zero under a common integrated envelope uniformly on compact times.','implementation gate'),
('bounded_local_volume_limit','The fixed bounded local evolution has a growing-region norm limit.','conditional'),
('gauge_invariance','The dynamics and selected observable preserve the local Gauss-invariant sector.','contract'),
('physical_local_bound','The full-space locality bound restricts to the physical invariant sector.','conditional'),
('compact_measure','The declared finite one-plaquette exponential tilt defines a probability measure on [-1,1].','contract'),
('haar_ibp','The compact integration-by-parts recurrence holds.','inherited proved result'),
('moment_positivity','Moment and support localizer matrices are positive semidefinite for the target measure.','derived'),
('rational_exclusion_gate','Every accepted endpoint exclusion is replayed in exact arithmetic.','implementation gate'),
('moment_outer_interval','The computed rational interval contains the true mean for the declared measure.','conditional'),
('variance_image_gate','The exact variance polynomial is enclosed on the entire mean interval, with a zero-tilt branch.','implementation gate'),
('variance_outer_interval','The computed interval contains the true variance.','conditional'),
('exponential_family_differentiation','Compact support permits differentiating the normalized exponential-family expectations.','derived'),
('susceptibility_identity','The derivative of the mean with respect to Euclidean tilt equals its strictly positive variance.','derived; independent review pending'),
('coupling_riccati','The regular one-plaquette mean obeys kappa*u_prime+3u=kappa*(1-u^2), u(0)=0, u_prime(0)=1/4.','derived; independent review pending'),
('vanishing_optimizer_slack','At one fixed finite real kappa, there exists a sequence of successfully replayed hierarchy levels r_j tending to infinity, with algorithm outer endpoints within certified eps_j tending to zero of the full feasible endpoints; finite support r<=6 does not supply this premise.','implementation gate'),
('algorithm_interval_convergence','Along successfully certified orders and precision, algorithm outer intervals converge to the true mean.','conditional'),
('all_order_constraints','At one fixed finite real kappa, m0=1 and every recurrence and support positivity constraint holds at all orders, not just finitely many.','hypothesis'),
('compact_moment_representation','Full support positivity provides a probability measure on [-1,1].','standard mathematical premise'),
('ibp_C1_extension','Polynomial insertion identities extend to all C1 insertions.','derived; independent review pending'),
('distribution_uniqueness','The interior distribution equation and endpoint test identify the exponential-Haar density.','derived; independent review pending'),
('hierarchy_unique','The complete compact hierarchy has the unique target moment sequence.','conditional; independent review pending'),
('nested_compact_relaxations','Relaxations are nested, nonempty, uniformly bounded and contain the true moments.','mathematical gate'),
('hierarchy_interval_convergence','The nested outer mean intervals converge to the exact mean, without a rate.','conditional; independent review pending'),
('yarotsky_primary','The primary product-vacuum stability theorem with possibly infinite-dimensional sites and existential constants c1,c2 is admitted under its exact hypotheses.','primary theorem'),
('electric_product_vacuum','Outgoing-link blocks have h_x=(4/3)sum_i C_xi, a unique constant vacuum and unit gap; alpha>0 is fixed.','derived; independent review pending'),
('finite_range_static_norm','Static real plaquette coefficients give bounded range-S perturbations with eta<=4*binom(d,2)*lambda_max/(3*alpha), uniformly in volume.','derived; independent review pending'),
('stability_smallness','The static perturbation satisfies eta<c1(S) and c2(S)*eta<1/2; constants are existential and no evaluated numerical coupling is thereby admitted.','explicit qualitative hypothesis'),
('admissible_stability_boundary','Use the source grouped empty-boundary family or the explicit padded free-halo/coefficient-mask embedding from weak-coupling-stability.md; constants keep the same interaction range.','derived; independent review pending'),
('uniform_full_hamiltonian_gap','The static finite-volume full link Hamiltonian has a unique vacuum and gap at least 3*alpha/8, uniformly over the declared volumes.','conditional'),
('gauge_vacuum_restriction','Local SU(2) gauge actions commute with the Hamiltonian; the unique vacuum carries the trivial one-dimensional character; the physical sector is reducing and contains it.','derived; independent review pending'),
('uniform_physical_hamiltonian_gap','The declared Gauss-restricted static finite-volume Hamiltonians retain the uniform lower gap 3*alpha/8.','conditional'),
('canonical_ground_state_limit','Under the same smallness conditions, the source grouped empty-boundary sequence has its canonical ground-state limit and self-adjoint GNS generator retaining the uniform gap.','conditional primary theorem'),
('canonical_physical_gap','The canonical limiting vacuum physical sector retains the fixed-spacing spectral lower bound; arbitrary-boundary universality and a continuum limit are not asserted.','conditional'),
('same_geometry_state_scale','The Euclidean and Hamiltonian branches have a proved matching of geometry, state and physical normalization.','open'),
('continuum_observables','Renormalized local observable families converge along a matched volume/spacing path.','open'),
('reconstruction_axioms','A limiting nontrivial theory satisfies required reconstruction and locality axioms.','open'),
('nontrivial_finite_energy','A nonzero physical observable has nontrivial finite-energy limiting spectral weight.','open'),
('uniform_physical_decay','A common strictly positive physical-time decay rate holds on a dense physical-state family.','open'),
('yang_mills_4d_gap','The required nontrivial pure four-dimensional Yang-Mills theory exists with a positive finite mass gap.','open target')]
claimrows=[dict(id=i,statement=s,status=t,scope='round13 advisor contract; exact implementation and scientific acceptance are separate') for i,s,t in claims]
rules=[
('L1',['link_tensor','onsite_selfadjoint','bounded_plaquettes'],'interaction_picture',1),
('L2',['interaction_picture','bounded_incidence','path_count'],'local_commutator_bound',1),
('L3',['local_commutator_bound','boundary_shell_sum'],'bounded_local_volume_limit',1),
('L4',['local_commutator_bound','gauge_invariance'],'physical_local_bound',1),
('M1',['compact_measure'],'haar_ibp',1),
('M2',['compact_measure'],'moment_positivity',1),
('M3',['haar_ibp','moment_positivity','rational_exclusion_gate'],'moment_outer_interval',1),
('M4',['moment_outer_interval','variance_image_gate'],'variance_outer_interval',1),
('M5',['all_order_constraints'],'compact_moment_representation',1),
('M6',['compact_moment_representation','all_order_constraints'],'ibp_C1_extension',1),
('M7',['ibp_C1_extension'],'distribution_uniqueness',1),
('M8',['distribution_uniqueness','compact_measure'],'hierarchy_unique',1),
('M9',['hierarchy_unique','nested_compact_relaxations'],'hierarchy_interval_convergence',1),
('M10',['compact_measure','exponential_family_differentiation'],'susceptibility_identity',1),
('M11',['susceptibility_identity','haar_ibp'],'coupling_riccati',1),
('M12',['hierarchy_interval_convergence','vanishing_optimizer_slack'],'algorithm_interval_convergence',1),
('Y1',['yarotsky_primary','electric_product_vacuum','finite_range_static_norm','stability_smallness','admissible_stability_boundary'],'uniform_full_hamiltonian_gap',1),
('Y2',['uniform_full_hamiltonian_gap','gauge_vacuum_restriction'],'uniform_physical_hamiltonian_gap',1),
('Y3',['yarotsky_primary','electric_product_vacuum','finite_range_static_norm','stability_smallness'],'canonical_ground_state_limit',1),
('Y4',['canonical_ground_state_limit','uniform_physical_hamiltonian_gap','gauge_vacuum_restriction'],'canonical_physical_gap',1),
('G1',['same_geometry_state_scale','continuum_observables','reconstruction_axioms','nontrivial_finite_energy','uniform_physical_decay'],'yang_mills_4d_gap',1)]
(root/'theorem_inventory.json').write_text(json.dumps(dict(version='round13-advisor-inventory-v1',claims=claimrows),indent=2,ensure_ascii=False)+'\n')
(root/'inference_rules.json').write_text(json.dumps(dict(version='round13-advisor-rules-v1',policy='Rules are public proof obligations. Hypotheses and implementation gates are not automatically admitted facts. Conditional mathematical arguments need independent review before promotion. A Horn route certifies replay only.',rules=[dict(id=i,premises=p,conclusion=c,cost=w,evidence='weak-coupling-stability.md' if i.startswith('Y') else 'advisor.md') for i,p,c,w in rules]),indent=2,ensure_ascii=False)+'\n')
roadmap=[
('R13-L','Connected-graph local dynamics','selected, implementation and independent review pending','A graph-independent bound for bounded observables with explicit boundary-distance decay.','Refuse total-volume constants, wrong incidence or implied norm-time continuity.','R12 NEXT-LOCAL'),
('R13-M','Exact rational compact moment bounds','selected, implementation and independent review pending','Exact endpoint exclusion, support matrices and an independent reference at held-out parameters.','Reject false closures, omitted support, sign/zero parameter mistakes.','R12 NEXT-MOMENTS'),
('R13-M-ALL','All-order compact hierarchy uniqueness and interval convergence','derived, independent review pending','Critic review of distribution equation, endpoint atoms, moment existence and diagonal compactness.','No finite-order equality or convergence rate asserted.','R13-M'),
('R13-P','Bidirectional dependency replay','selected, integration pending','Actual forward/backward meeting for local and moment branches with negative controls.','Final target remains unreachable when physical-scale and reconstruction premises are absent.','R13-L and R13-M'),
('R13-Y','Qualitative fixed-spacing Hamiltonian gap stability','derived applicability; independent review pending','Exact infinite-dimensional primary theorem match, boundary padding, Gauss restriction and qualitative smallness.','No numerical smallness threshold or continuum transfer asserted.','Yarotsky primary theorem'),
('NEXT-Y-CONSTANTS','Quantitative stability threshold','open','Extract and independently replay explicit constants for the actual finite interaction range.','Existential constants cannot classify a numerical coupling as certified.','R13-Y'),
('NEXT-GROUND','Ground states beyond the small static perturbation regime','open','Construct compatible states and identify a positive limiting generator.','A locality bound alone is not a gap.','R13-L'),
('NEXT-LOOPS','Moment constraints on interacting loop observables','open','Derive exact shared-link identities and positivity matrices for connected graphs.','One-plaquette Gibbs moments are not coupled Hamiltonian ground-state moments.','R13-M'),
('NEXT-DEFORM','Controlled removal of a deformation','optional research route, open','Same observable family, explicit action and uniform errors along compactification/deformation path.','Do not assume absence of a phase transition or interchange large-N and circle limits.','C10'),
('NEXT-CONTINUUM','Four-dimensional construction and physical gap','open','Matched scale limits, nontriviality, reconstruction and positive physical rate on a dense sector.','No present finite-model result supplies these hypotheses.','Round12 unresolved central obligation')]
(root/'roadmap.json').write_text(json.dumps(dict(version='round13-advisor-roadmap-v1',date='2026-09-09',policy='Proposed statuses must be reconciled with completed independent evidence before site publication; historical round12 records remain immutable.',items=[dict(id=i,title=t,status=s,acceptance=a,rejection=r,origin=o) for i,t,s,a,r,o in roadmap]),indent=2,ensure_ascii=False)+'\n')
files=['advisor.md','sources.json','case_matrix.json','theorem_inventory.json','inference_rules.json','roadmap.json','weak-coupling-stability.md','weak-coupling-stability-source.json']
(root/'artifact_manifest.json').write_text(json.dumps(dict(files={f:hashlib.sha256((root/f).read_bytes()).hexdigest() for f in files}),indent=2)+'\n')
print('Saved',len(sources),'primary sources;',len(cases),'case routes;',len(claims),'claims;',len(rules),'rules.')
