"""Verify an exact detached release tree and write its receipt outside the repo."""
import argparse
import hashlib
import json
from pathlib import Path
import runpy
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[3]
BASE = '7ab3c276b576d13040b2069539f9e712861edb2f'


def require(ok, message):
    if not ok:
        raise ValueError(message)


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()


def digest(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--expected-commit', required=True)
    p.add_argument('--expected-tree', required=True)
    p.add_argument('--output', required=True, type=Path)
    a = p.parse_args(); out = a.output.resolve()
    require(not out.exists() and not out.is_relative_to(ROOT), 'fresh external output')
    out.mkdir(parents=True)
    require(git('rev-parse', 'HEAD') == a.expected_commit, 'candidate commit')
    require(git('rev-parse', 'HEAD^{tree}') == a.expected_tree, 'candidate tree')
    require(git('rev-parse', '--abbrev-ref', 'HEAD') == 'HEAD', 'detached checkout required')
    require(not git('status', '--porcelain'), 'candidate must start clean')
    changed = git('diff', '--name-only', BASE, 'HEAD', '--', 'research', 'evidence').splitlines()
    require(all(x.startswith('research/round26/') for x in changed), 'historical research changed')
    sys.path.insert(0, str(ROOT / 'research/round26'))
    from admission import hashes
    review = json.loads((ROOT / 'research/round26/skeptic/release-review.json').read_text())
    require(review.get('verdict') == 'accepted_within_scope' and review.get('blocking_issues') == [], 'presentation review not admitted')
    hashes(review['sha256'])
    required_presentation = {'README.md', 'dist/index.html', 'dist/research-round26.js', 'dist/research-round26.css',
        'dist/research-round26-data.js', 'research/round26/HANDOFF.md', 'research/round26/NOVELTY.md',
        'research/round26/advisor/roadmap.json', 'research/round26/advisor/summaries.json',
        'research/round26/advisor/network-extensions.json', 'research/round26/build_site.py',
        'research/round26/admission.py', 'research/round26/release/verify.py', 'tests/test_round26.mjs'}
    require(required_presentation <= review['sha256'].keys(), 'review lacks current presentation/source inventory')
    methods = json.loads((ROOT / 'research/round26/methods/prospective-updates.json').read_text())
    for item in methods['updates']:
        hashes(item['snapshots'])
    archived = runpy.run_path(str(ROOT / 'research/round24/admission.py'))
    for loop in archived['LOOPS']:
        archived['gate'](loop)
    checks = []
    def run(name, cmd):
        result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        (out / (name + '.log')).write_text(result.stdout + result.stderr)
        require(result.returncode == 0, 'failed ' + name + '; see ' + str(out / (name + '.log')))
        checks.append({'name': name, 'command': cmd, 'exit_code': 0})
        print(name + ': passed', flush=True)
    for optimized in [False, True]:
        mode = 'optimized' if optimized else 'normal'
        py = [sys.executable, '-B'] + (['-O'] if optimized else [])
        option = ['--optimized'] if optimized else []
        run('round26-' + mode, py + ['research/round26/admission.py', '--output', str(out / ('round26-' + mode)), *option])
        run('inherited-aa-' + mode, py + ['research/round25/admission.py', '--output', str(out / ('aa-' + mode)), *option])
        run('admission-mutations-' + mode, py + ['research/round26/test_admission.py'])
    generated = [ROOT / 'dist/research-round26-data.js', ROOT / 'research/round26/network.json',
                 *[p for p in (ROOT / 'docs').iterdir() if p.is_file()]]
    expected = {str(p.relative_to(ROOT)): digest(p) for p in generated}
    (ROOT / 'dist/research-round26-data.js').unlink()
    (ROOT / 'research/round26/network.json').unlink()
    shutil.rmtree(ROOT / 'docs')
    run('new-data-rebuild', [sys.executable, '-B', 'research/round26/build_site.py'])
    run('pages-rebuild', [sys.executable, '-B', 'scripts/build_pages.py'])
    require(all((ROOT / name).is_file() and digest(ROOT / name) == h for name, h in expected.items()),
            'generated bytes differ')
    for name in ['test_workbench', 'test_journey', 'test_round22', 'test_round23', 'test_round24', 'test_round25', 'test_round26']:
        run(name, ['node', 'tests/' + name + '.mjs'])
    require(not git('status', '--porcelain'), 'verification changed candidate')
    receipt = {'status': 'passed', 'commit': a.expected_commit, 'tree': a.expected_tree,
               'baseline': BASE, 'new_research_loops': 10, 'current_producer_replays': 40,
               'inherited_producer_replays': 4, 'generated_files_compared': len(expected),
               'checks': checks, 'scope': 'exact-tree source integrity, producer replay, rebuild and interface tests',
               'browser_visual_review': 'Local cloud-browser preview was blocked; live-page review recorded after publication.',
               'review': 'separate model-agent mathematical review; not external peer review or formal proof'}
    (out / 'receipt.json').write_text(json.dumps(receipt, indent=2) + '\n')
    print(json.dumps({'status': 'passed', 'receipt_sha256': digest(out / 'receipt.json')}))


if __name__ == '__main__':
    main()
