"""Verify the exact clean detached tree of a completed ten-loop Round28 release.

Run only in a fresh disposable worktree. Receipts stay outside their tested Git
tree. A working prefix uses reproduce.py; this final gate requires all ten loops.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

sys.dont_write_bytecode = True
from reproduce import BASE, PREFIX, ROOT, Validator, digest, require

PORTABILITY_APPROVAL = PREFIX + "advisor/ah-portability-admission.json"
PORTABILITY_APPROVAL_SHA = "339bf78392a62a8b87230d4277710f4a2bdd131e4e3b0c00e044d327aaa52092"


def git(*arguments):
    return subprocess.check_output(["git", *arguments], cwd=ROOT, text=True).strip()


def inventory(relative):
    directory = ROOT / relative
    require(directory.is_dir(), "missing release subtree: " + relative)
    files = {}
    for path in sorted(directory.rglob("*")):
        require(not path.is_symlink(), "linked path in release subtree: " + str(path))
        if path.is_file():
            require("__pycache__" not in path.parts and path.suffix not in {".pyc", ".pyo"}, "interpreter cache in release subtree")
            files[str(path.relative_to(ROOT))] = digest(path)
    return files


def committed_inventory(relative):
    tracked = {name for name in git("ls-tree", "-rz", "--name-only", "HEAD", "--", relative).split("\0") if name}
    actual = inventory(relative)
    require(tracked and set(actual) == tracked, "working subtree differs from committed file set: " + relative)
    return actual


def checker_command(checker, destination, optimized):
    script = checker.get("script")
    require(isinstance(script, str) and script.startswith(PREFIX + "skeptic/") and script.endswith(".py"), "invalid skeptic entrypoint")
    arguments = checker.get("arguments", [])
    require(isinstance(arguments, list) and all(isinstance(x, str) for x in arguments), "invalid skeptic argument vector")
    mode = checker.get("output_mode", "fixed")
    require(mode in {"file", "directory", "fixed"}, "unknown skeptic output interface")
    require(mode == "fixed" or arguments.count("{output}") == 1, "fresh skeptic output placeholder required")
    require(mode != "fixed" or "{output}" not in arguments, "fixed checker has unexpected output substitution")
    require(all("{" not in x and "}" not in x for x in arguments if x != "{output}"), "unsupported command template")
    return [sys.executable, "-B"] + (["-O"] if optimized else []) + [str(ROOT / script)] + [
        str(destination) if x == "{output}" else x for x in arguments]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--expected-commit", required=True)
    parser.add_argument("--expected-tree", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    for identity in [args.expected_commit, args.expected_tree]:
        require(re.fullmatch(r"(?:[0-9a-f]{40}|[0-9a-f]{64})", identity), "full Git identity required")
    require(args.output.is_absolute(), "absolute receipt directory required")
    out = args.output.resolve()
    require(not out.exists() and not out.is_relative_to(ROOT), "fresh external receipt directory required")
    require(git("rev-parse", "HEAD") == args.expected_commit and git("rev-parse", "HEAD^{tree}") == args.expected_tree,
            "candidate commit/tree mismatch")
    require(git("rev-parse", "--abbrev-ref", "HEAD") == "HEAD", "fresh detached worktree required")
    require(not git("status", "--porcelain", "--untracked-files=all"), "candidate must start clean")
    changed = git("diff", "--name-only", BASE, "HEAD", "--", "research", "evidence").splitlines()
    require(all(name.startswith(PREFIX) for name in changed), "historical science changed")
    old_papers = set(git("ls-tree", "-r", "--name-only", BASE, "--", "papers").splitlines())
    paper_changes = set(git("diff", "--name-only", BASE, "HEAD", "--", "papers").splitlines())
    require(not old_papers.intersection(paper_changes), "historical paper artifact changed")
    validator = Validator()
    selected, completed, _ = validator.sequence(complete=True)
    out.mkdir(parents=True)
    receipt = {"schema": "ym28-exact-tree-release-receipt-v1", "status": "running", "commit": args.expected_commit,
               "tree": args.expected_tree, "baseline": BASE, "completed_research_loops": completed,
               "additional_research_loops_in_verification": 0, "checks": [],
               "scope": "current ten-loop source integrity, normal/optimized replay, exact generated bytes and targeted UI; no continuum certification"}

    def run(name, command):
        result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
        logfile = out / (name + ".log")
        logfile.write_text(result.stdout + result.stderr)
        receipt["checks"].append({"name": name, "command": command, "exit_code": result.returncode,
                                   "log": str(logfile), "log_sha256": digest(logfile)})
        require(result.returncode == 0, "failed " + name + "; see " + str(logfile))
        print(name + ": passed", flush=True)

    try:
        require(digest(validator.source(PORTABILITY_APPROVAL)) == PORTABILITY_APPROVAL_SHA,
                "administrative portability approval changed")
        portability = validator.load(PORTABILITY_APPROVAL)
        require(portability.get("accepted") is True and portability.get("new_research_loops") == 0
                and portability.get("allowed_substitutions") == ["ah1/reverse", "ah2/reverse"],
                "unapproved portability substitution")
        validator.hashes(portability["bindings"])
        review = validator.load(portability["review"])
        require(review.get("accepted") is True and review.get("blocking_issues") == [],
                "independent portability review missing")
        validator.hashes(review["bindings"])
        receipt["administrative_portability_repair"] = {
            "approval_sha256": PORTABILITY_APPROVAL_SHA,
            "manifest_sha256": portability["manifest_sha256"],
            "original_scripts_per_mode": 18, "portable_copies_per_mode": 2,
            "original_scientific_admissions_changed": False}
        admissions = [validator.validate(loop) for loop in completed]
        before = {name: committed_inventory(name) for name in ["research/round28", "dist", "docs"]}
        for optimized in [False, True]:
            mode = "optimized" if optimized else "normal"
            py = [sys.executable, "-B"] + (["-O"] if optimized else [])
            audit_destination = out / ("portability-audit-" + mode + ".json")
            run("portability-audit-" + mode, py + [portability["audit"]["script"], "--output", str(audit_destination)])
            require(audit_destination.read_bytes() == validator.source(portability["audit"]["output"]).read_bytes(),
                    "portable audit replay bytes differ: " + mode)
            run("producer-replay-" + mode, py + [portability["runner"], "--manifest-sha256",
                portability["manifest_sha256"], "--output", str(out / ("producers-" + mode))]
                + (["--optimized"] if optimized else []))
            run("admission-mutations-" + mode, py + [PREFIX + "test_admission.py"])
        receipt["producer_executions"] = 4 * len(completed)
        skeptic_runs = []
        for record in admissions:
            loop = record["loop"]
            for number, checker in enumerate(record["skeptic_checkers"]):
                stored = validator.source(checker["output"])
                expected = stored.read_bytes()
                for optimized in [False, True]:
                    mode = "optimized" if optimized else "normal"
                    label = f"skeptic-{loop}-{number + 1}-{mode}"
                    destination = out / (label + ".json")
                    output_mode = checker.get("output_mode", "fixed")
                    if output_mode == "directory":
                        destination = out / label
                    command = checker_command(checker, destination, optimized)
                    run(label, command)
                    produced = (stored if output_mode == "fixed" else destination / checker.get("result_name", "results.json")
                                if output_mode == "directory" else destination)
                    require(produced.is_file() and produced.read_bytes() == expected, "skeptic replay bytes differ: " + label)
                    skeptic_runs.append({"loop": loop, "script": checker["script"], "optimized": optimized,
                                         "results_sha256": digest(produced)})
        receipt["skeptic_replays"] = skeptic_runs
        run("round28-final-paper-manifest", [sys.executable, "-B", "papers/round28-addendum/artifact_manifest.py", "--check"])
        # Build destinations are deliberate and limited to the disposable tree.
        generated = [ROOT / PREFIX / "network.json", ROOT / "dist/research-round28-data.js"]
        for path in generated:
            require(path.is_file(), "generated Round28 baseline missing: " + str(path))
            path.unlink()
        shutil.rmtree(ROOT / "docs")
        run("round28-network-build", [sys.executable, "-B", PREFIX + "build_network.py", "--require-complete"])
        run("round28-site-builder-controls", [sys.executable, "-B", "tests/round28_build.py"])
        run("round28-data-build", [sys.executable, "-B", PREFIX + "build_site.py", "--require-complete"])
        run("pages-build", ["npm", "run", "build"])
        for name, expected in before.items():
            require(inventory(name) == expected, "rebuilt subtree differs from committed baseline: " + name)
        receipt["compared_subtree_file_counts"] = {name: len(files) for name, files in before.items()}
        run("round28-release-ui", ["node", "tests/round28_site.mjs", "--release"])
        for name in ["test_round27", "test_workbench"]:
            require((ROOT / "tests" / (name + ".mjs")).is_file(), "targeted UI test absent: " + name)
            run(name, ["node", "tests/" + name + ".mjs"])
        require(not git("status", "--porcelain", "--untracked-files=all"), "release verification changed candidate")
        require(git("rev-parse", "HEAD") == args.expected_commit and git("rev-parse", "HEAD^{tree}") == args.expected_tree,
                "candidate identity changed during release")
        receipt["status"] = "passed"
        receipt["clean_before_and_after"] = True
    except Exception as error:
        receipt["status"] = "failed"
        receipt["failure"] = str(error)
        receipt["final_git_status"] = git("status", "--porcelain", "--untracked-files=all")
        raise
    finally:
        path = out / "receipt.json"
        path.write_text(json.dumps(receipt, indent=2) + "\n")
        checksum = digest(path)
        (out / "receipt.sha256").write_text(checksum + "  receipt.json\n")
        print(json.dumps({"status": receipt["status"], "receipt": str(path), "receipt_sha256": checksum}))


if __name__ == "__main__":
    main()
